# **Day 10 - Pandas for Biomedical Data Analysis**
Author: Jagriti Singh

Course: Python for Computational Biology

Repository: Python-for-Biologists

##  Notebook Roadmap

| Part | Topic | Goal |
|:----:|-------|------|
|  10A | Introduction & Dataset Creation | Create a realistic LUAD gene expression dataset |
|  10B | Loading & Exploring Dataset | Understand dataset structure using Pandas |
|  10C | Statistical Analysis | Calculate descriptive statistics and interpret results |
|  10D | Filtering & Sorting | Identify biologically relevant genes |
|  10E | Missing Values | Detect, clean, and prepare data |
|  10F | Mini Research Project | Perform an end-to-end analysis workflow |
|  10G | Reflection & Research Notes | Connect learning to transcriptomic research |
|  10H | Summary  | Consolidate concepts and prepare for visualization |

# **Introduction**
Modern biomedical research generates large tabular datasets containing thousands of genes and their expression values.

These datasets are commonly stored as CSV files and analyzed using Pandas.

Examples include:

• RNA-Seq gene expression matrices

• Clinical metadata

• Differential gene expression tables

• Mutation datasets

• Drug response data

Pandas is the most widely used Python library for handling structured biological data.

This notebook introduces Pandas using a realistic gene expression dataset.

# **Why Pandas Matters**
Pandas is used in nearly every computational biology workflow.

Researchers use Pandas to:

• Load CSV files

• Clean biological datasets

• Filter genes

• Handle missing values

• Calculate statistics

• Merge datasets

• Prepare data for machine learning

Without Pandas, analyzing thousands of genes becomes extremely difficult.

# **Learning Objectives**
After completing this notebook, I will be able to:

* Import CSV datasets

* Explore gene expression tables

* Calculate summary statistics

* Filter highly expressed genes

* Identify missing values

* Sort expression values

* Interpret biological results

* Prepare datasets for downstream analysis

# **Research Connection**
This notebook is directly relevant to my undergraduate
research on the transcriptome-based analysis of competing
endogenous RNA (ceRNA) networks associated with lung
adenocarcinoma prognosis.

Learning Pandas enables me to analyze transcriptomic
datasets using Python rather than relying solely on
web-based bioinformatics platforms.

These skills form the computational foundation for
future work in cancer genomics, bioinformatics,
biomedical data science, and AI-driven healthcare.

###  RNA-Seq Data Analysis Workflow

```text
           LUAD Gene List
                  │
                  ▼
       Generate CSV Dataset
                  │
                  ▼
       Load Dataset using Pandas
                  │
                  ▼
       Explore Dataset Structure
                  │
                  ▼
       Data Cleaning & Quality Control
                  │
                  ▼
       Statistical Analysis
                  │
                  ▼
       Data Visualization
                  │
                  ▼
       Biological Interpretation
                  │
                  ▼
       Machine Learning Preparation
```

# **Google Colab Setup**


Before writing any code, ensure that

* Google Colab notebook is open

* Runtime is connected

* A new Code Cell is created

To create a new Code Cell

Insert → Code Cell

**or**

+ Code

To create a Markdown Cell

Insert → Text Cell

**or**

+ Text

Run a code cell using

Shift + Enter

**or**

Click

In [ ]:
#Import Libraries
import pandas as pd
import numpy as np

# **Explanation**

Pandas is the primary library used for handling structured
datasets.

NumPy provides numerical computing capabilities.

Nearly every computational biology workflow begins by
importing these two libraries.

In [ ]:
#Random Seed
np.random.seed(42)

# **Why use np.random.seed(42)?**

Random numbers are often used to generate simulated datasets.

Without fixing the seed, the values change every time
the notebook is executed.

Setting

np.random.seed(42)

ensures that the same dataset is generated every time.

This improves reproducibility, which is one of the most
important principles in scientific research.

# **Dataset Design**
##  Designing a Transcriptomic Dataset

The dataset will simulate gene expression values obtained
from a lung adenocarcinoma (LUAD) transcriptomic study.

Each row represents one gene.

Each column describes one biological characteristic.

# **Dataset Columns**
| Column           | Description                 | Why it Matters            |
| ---------------- | --------------------------- | ------------------------- |
| Gene             | Gene Symbol                 | Identifies the gene       |
| Expression       | Normalized Expression       | Quantitative analysis     |
| Cancer_Type      | Cancer Type                 | Disease classification    |
| Chromosome       | Chromosome Number           | Genomic location          |
| Gene_Type        | Oncogene / Tumor Suppressor | Biological interpretation |
| Log2FC           | Log₂ Fold Change            | Differential expression   |
| P_Value          | Statistical significance    | Hypothesis testing        |
| Adjusted_P_Value | FDR corrected p-value       | Reliable significance     |
| Status           | Upregulated / Downregulated | Biological conclusion     |

### **Why these columns?**

These variables resemble the output generated after
RNA sequencing differential gene expression analysis.

Such datasets are commonly obtained from

• TCGA

• GEO

• ArrayExpress

• cBioPortal

• Cancer transcriptomics studies

In [ ]:
import pandas as pd
import numpy as np

# Make results reproducible
np.random.seed(42)

genes = [
    "TP53","BRCA1","EGFR","KRAS","MYC","ALK","BRAF","PIK3CA","CDK4","PTEN",
    "RB1","CCND1","ERBB2","MET","FGFR1","VEGFA","CDH1","SMAD4","APC","NRAS",
    "AKT1","MTOR","NOTCH1","JAK2","STAT3","NFKB1","HIF1A","MDM2","TERT","CDKN2A",
    "ATM","ATR","CHEK1","CHEK2","BCL2","BAX","CASP3","FAS","MMP9","CXCL8",
    "IL6","TGFB1","PDCD1","CD274","CTLA4","LAG3","TIGIT","IFNG","GZMB","PRF1",
    "SOX2","NANOG","POU5F1","VIM","EPCAM","SNAI1","TWIST1","ZEB1","MUC1","KRT18",
    "KRT19","COL1A1","FN1","ITGA6","ITGB1","CXCR4","CCR7","MKI67","PCNA","TOP2A",
    "GATA3","FOXA1","ESR1","AR","RUNX1","IDH1","IDH2","FLT3","KIT","ROS1",
    "RET","NTRK1","NTRK2","NTRK3","SMARCA4","ARID1A","KEAP1","STK11","NF1","NF2",
    "BRIP1","PALB2","RAD51","XRCC1","MSH2","MSH6","MLH1","PMS2","POLE","POLD1"
]

n = len(genes)

df = pd.DataFrame({
    "Gene": genes,
    "Expression": np.round(np.random.uniform(5, 25, n), 2),
    "Cancer_Type": ["LUAD"] * n,
    "Chromosome": np.random.randint(1, 23, n),
    "Gene_Type": np.random.choice(
        ["Oncogene", "Tumor Suppressor"],
        n
    ),
    "Log2FC": np.round(np.random.uniform(-4, 4, n), 2),
    "P_Value": np.round(np.random.uniform(0.0001, 0.05, n), 4),
    "Adjusted_P_Value": np.round(np.random.uniform(0.0001, 0.05, n), 4)
})

df["Status"] = np.where(df["Log2FC"] > 0,
                        "Upregulated",
                        "Downregulated")

df.head()

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
0,TP53,12.49,LUAD,7,Oncogene,0.62,0.0008,0.0309,Upregulated
1,BRCA1,24.01,LUAD,17,Oncogene,-0.06,0.0059,0.0051,Downregulated
2,EGFR,19.64,LUAD,20,Tumor Suppressor,-2.44,0.0024,0.0043,Downregulated
3,KRAS,16.97,LUAD,4,Tumor Suppressor,1.78,0.0021,0.0351,Upregulated
4,MYC,8.12,LUAD,5,Oncogene,-1.75,0.0428,0.0037,Downregulated

### **Explanation**

This code generates a simulated transcriptomic dataset
containing approximately 100 cancer-associated genes.

The numerical values are randomly generated but
scientifically realistic for learning purposes.

Although simulated, the structure resembles real
RNA-Seq differential expression datasets.

In [ ]:
df.head()

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
0,TP53,12.49,LUAD,7,Oncogene,0.62,0.0008,0.0309,Upregulated
1,BRCA1,24.01,LUAD,17,Oncogene,-0.06,0.0059,0.0051,Downregulated
2,EGFR,19.64,LUAD,20,Tumor Suppressor,-2.44,0.0024,0.0043,Downregulated
3,KRAS,16.97,LUAD,4,Tumor Suppressor,1.78,0.0021,0.0351,Upregulated
4,MYC,8.12,LUAD,5,Oncogene,-1.75,0.0428,0.0037,Downregulated

# **Explanation**

The head() function displays the first five rows of the dataset.

Researchers use this function immediately after loading
a dataset to verify that the data were imported correctly.

This is usually the first quality control step in
computational biology analyses.

In [ ]:
df.to_csv(
    "LUAD_Gene_Expression_Dataset.csv",
    index=False
)

print("Dataset saved successfully!")

Dataset saved successfully!

# **Explanation**

The dataset has now been saved as a CSV file.

CSV (Comma-Separated Values) is one of the most common
formats used in computational biology because it is
supported by Python, R, Excel, SPSS, and most
bioinformatics software.

In [ ]:
import os

os.listdir()

['.config', 'LUAD_Gene_Expression_Dataset.csv', 'sample_data']

# **Explanation**

The os.listdir() function displays every file currently
available in the Google Colab working directory.

If

LUAD_Gene_Expression_Dataset.csv

appears in the output, the dataset has been created
successfully.

In [ ]:
from google.colab import files

files.download("LUAD_Gene_Expression_Dataset.csv")

# **Why download the dataset?**

Downloading the dataset allows you to

* Keep a permanent copy

* Upload it to GitHub

* Reuse it in future notebooks

* Analyze it using R or Excel

* Share it with collaborators

# **Day 10-A Summary**


In this notebook, I learned how to prepare a realistic
transcriptomic dataset for computational biology.

Using Pandas and NumPy, I generated a reproducible
lung adenocarcinoma gene expression dataset, explored
its structure, and saved it as a CSV file.

This dataset will serve as the foundation for all
subsequent analyses, including data exploration,
statistical analysis, visualization, and bioinformatics
workflows.

# **Day 10B – Loading & Exploring a Biomedical Dataset**
## Loading and Exploring the Gene Expression Dataset

After creating the LUAD gene expression dataset in Part 10A, the next step is to load it into Pandas and perform an initial exploration.

In computational biology, every dataset should be examined before analysis to understand its structure, dimensions, data types, and overall quality.

This process is known as **Exploratory Data Analysis (EDA)** and is one of the first steps performed in transcriptomics, genomics, and biomedical data science.

Typical questions researchers ask include:

- How many genes are present?
- What variables are available?
- Are there any missing values?
- What are the data types?
- Is the dataset ready for downstream analysis?

In [ ]:
#import
import pandas as pd

# **Explanation**
### Why import Pandas?

Pandas is the most widely used Python library for handling structured data.

It allows researchers to:

- Import CSV files
- Organize biological datasets into tables (DataFrames)
- Filter genes
- Calculate statistics
- Detect missing values
- Prepare data for machine learning

Almost every computational biology workflow begins by importing Pandas.

In [ ]:
#Load the Dataset
df = pd.read_csv("LUAD_Gene_Expression_Dataset.csv")

df

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
0,TP53,12.49,LUAD,7,Oncogene,0.62,0.0008,0.0309,Upregulated
1,BRCA1,24.01,LUAD,17,Oncogene,-0.06,0.0059,0.0051,Downregulated
2,EGFR,19.64,LUAD,20,Tumor Suppressor,-2.44,0.0024,0.0043,Downregulated
3,KRAS,16.97,LUAD,4,Tumor Suppressor,1.78,0.0021,0.0351,Upregulated
4,MYC,8.12,LUAD,5,Oncogene,-1.75,0.0428,0.0037,Downregulated
...,...,...,...,...,...,...,...,...,...
95,MSH6,14.88,LUAD,18,Oncogene,0.89,0.0444,0.0137,Upregulated
96,MLH1,15.45,LUAD,8,Tumor Suppressor,-0.64,0.0176,0.0029,Downregulated
97,PMS2,13.55,LUAD,1,Oncogene,-2.02,0.0059,0.0432,Downregulated
98,POLE,5.51,LUAD,11,Tumor Suppressor,-1.15,0.0072,0.0407,Downregulated
99,POLD1,7.16,LUAD,18,Oncogene,2.06,0.0381,0.0500,Upregulated

# **Explanation**
**Understanding `read_csv()`**

The function `pd.read_csv()` reads a CSV (Comma-Separated Values) file and converts it into a Pandas **DataFrame**.

A DataFrame is similar to a spreadsheet or database table where:

- Each row represents one observation (gene).
- Each column represents one variable (expression, chromosome, p-value, etc.).

# **Biological Interpretation**

In this notebook:

- Each row corresponds to one gene associated with Lung Adenocarcinoma (LUAD).
- Each column contains biological information about that gene.

This structure is similar to datasets downloaded from repositories such as TCGA or GEO.

In [ ]:
#Display the First Five Rows
df.head()

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
0,TP53,12.49,LUAD,7,Oncogene,0.62,0.0008,0.0309,Upregulated
1,BRCA1,24.01,LUAD,17,Oncogene,-0.06,0.0059,0.0051,Downregulated
2,EGFR,19.64,LUAD,20,Tumor Suppressor,-2.44,0.0024,0.0043,Downregulated
3,KRAS,16.97,LUAD,4,Tumor Suppressor,1.78,0.0021,0.0351,Upregulated
4,MYC,8.12,LUAD,5,Oncogene,-1.75,0.0428,0.0037,Downregulated

# **Explanation**
**Exploring the Dataset with `head()`**

The `head()` function displays the **first five rows** of the dataset.

Researchers commonly use this function immediately after loading a dataset to verify that:

- The file loaded correctly.
- Column names are accurate.
- Data appears in the expected format.
- No obvious formatting issues are present.

# **Biological Interpretation**

The first few rows provide a quick overview of:

- Gene symbols
- Expression values
- Cancer type
- Chromosome location
- Gene classification
- Statistical significance

This helps researchers understand the biological content before deeper analysis.

In [ ]:
#Display the Last Five Rows
df.tail()

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
95,MSH6,14.88,LUAD,18,Oncogene,0.89,0.0444,0.0137,Upregulated
96,MLH1,15.45,LUAD,8,Tumor Suppressor,-0.64,0.0176,0.0029,Downregulated
97,PMS2,13.55,LUAD,1,Oncogene,-2.02,0.0059,0.0432,Downregulated
98,POLE,5.51,LUAD,11,Tumor Suppressor,-1.15,0.0072,0.0407,Downregulated
99,POLD1,7.16,LUAD,18,Oncogene,2.06,0.0381,0.0500,Upregulated

# **Explanation**
### **Exploring the Dataset with `tail()`**

The `tail()` function displays the **last five rows** of the dataset.

Researchers use this function to:

- Confirm that the entire dataset was imported.
- Inspect the final records.
- Detect accidental truncation or incomplete imports.

# **Biological Interpretation**

Viewing the last few genes ensures that the dataset contains all expected observations before analysis begins.

In [ ]:
#Determine the Dataset Dimensions
df.shape

(100, 9)

# **Explanation**
**Understanding `shape`**

The `shape` attribute returns:

```
(Number of Rows, Number of Columns)
```

For example:

```
(100, 9)
```

means:

- 100 genes
- 9 variables

### Why is this important?

Researchers first determine the size of a dataset before performing analyses.

Large transcriptomic datasets may contain:

- 20,000–60,000 genes
- Hundreds of biological variables
- Thousands of patient samples

Understanding dataset dimensions helps estimate computational requirements and guides subsequent analyses.

In [ ]:
#Display Column Names
df.columns

Index(['Gene', 'Expression', 'Cancer_Type', 'Chromosome', 'Gene_Type',
       'Log2FC', 'P_Value', 'Adjusted_P_Value', 'Status'],
      dtype='object')

# **Explanation**

**Understanding `columns`**

The `columns` attribute displays the names of all variables in the dataset.

Expected columns include:

- Gene
- Expression
- Cancer_Type
- Chromosome
- Gene_Type
- Log2FC
- P_Value
- Adjusted_P_Value
- Status

### Why is this important?

Researchers inspect column names to ensure that variables have been imported correctly and are ready for analysis.

Accurate column names are essential when filtering, sorting, or visualizing data.

In [ ]:
#Display Data Types and Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gene              100 non-null    object
 1   Expression        100 non-null    float64
 2   Cancer_Type       100 non-null    object
 3   Chromosome        100 non-null    int64
 4   Gene_Type         100 non-null    object
 5   Log2FC            100 non-null    float64
 6   P_Value           100 non-null    float64
 7   Adjusted_P_Value  100 non-null    float64
 8   Status            100 non-null    object
dtypes: float64(4), int64(1), object(4)
memory usage: 7.2+ KB

# **Explanation**

## Understanding `info()`

The `info()` function provides a concise summary of the dataset, including:

- Number of rows
- Number of columns
- Column names
- Data types
- Number of non-null values
- Memory usage

### Common Data Types

| Data Type | Meaning | Example |
|-----------|---------|---------|
| object | Text/String | TP53 |
| int64 | Integer | Chromosome number |
| float64 | Decimal values | Gene expression |
| bool | True/False | Logical variables |

### Biological Interpretation

Checking data types ensures that:

- Gene names are stored as text.
- Expression values are numerical.
- P-values are numeric.
- Chromosome numbers are integers.

Incorrect data types can lead to errors during statistical analysis or visualization.

In [ ]:
#Count Rows and Columns Separately
print("Number of Genes:", df.shape[0])
print("Number of Variables:", df.shape[1])

Number of Genes: 100
Number of Variables: 9

# **Interpreting Dataset Dimensions**

Using `shape[0]` returns the number of rows (genes).

Using `shape[1]` returns the number of columns (variables).

# **Biological Interpretation**

In this simulated LUAD dataset:

- Each gene represents a unique biological observation.
- Each variable describes a different characteristic of that gene.

Understanding the number of observations and variables helps researchers assess the scope of their dataset before performing downstream analyses.

# **Research Note**

Loading and exploring a dataset is one of the first steps in any computational biology project.

Before performing differential expression analysis, pathway enrichment, or machine learning, researchers verify that the dataset:

- Has been imported correctly.
- Contains the expected variables.
- Uses appropriate data types.
- Is free from obvious formatting issues.

This quality-control step helps prevent errors in downstream analyses and ensures that biological conclusions are based on reliable data.

# **Reflection**

During my undergraduate dissertation on the transcriptome-based analysis of competing endogenous RNA (ceRNA) networks associated with lung adenocarcinoma prognosis, gene expression datasets were explored primarily through web-based bioinformatics platforms.

By learning how to load and inspect datasets using Pandas, I can now independently examine transcriptomic data, verify dataset quality, and prepare biological data for further computational analyses. These skills strengthen my ability to perform reproducible and scalable biomedical research using Python.

# **Key Takeaways


- Successfully imported a CSV file into a Pandas DataFrame.
- Explored the dataset using `head()` and `tail()`.
- Examined dataset dimensions with `shape`.
- Identified variables using `columns`.
- Inspected data types and missing values using `info()`.
- Understood why exploratory data analysis (EDA) is the first step in computational biology workflows.

# **Part 10-B Summary**

In this section, I learned how to load a biological dataset into a Pandas DataFrame and perform an initial exploration of its structure. I used functions such as `read_csv()`, `head()`, `tail()`, `shape`, `columns`, and `info()` to inspect the dataset and verify that it was imported correctly.

These exploratory steps are essential in computational biology because they help researchers understand the organization, dimensions, and data types of a dataset before performing statistical analyses or downstream bioinformatics workflows. Proper dataset exploration ensures data quality and reduces the likelihood of errors during analysis.

# **Part 10C - Descriptive Statistical Analysis of Gene Expression Data**
After loading and exploring a biological dataset, the next step is to summarize its numerical characteristics.

Descriptive statistics provide a quick overview of the distribution of gene expression values and help researchers identify important trends before performing downstream analyses.

In computational biology, descriptive statistics are routinely used for:

- RNA-Seq gene expression studies
- Microarray experiments
- Differential gene expression analysis
- Cancer biomarker discovery
- Clinical transcriptomics
- Quality assessment of biological datasets

Instead of inspecting hundreds or thousands of expression values individually, researchers use descriptive statistics to understand the overall characteristics of the dataset.

# **Biological Importance**

**Why Descriptive Statistics Matter**?

Large-scale biological datasets often contain thousands of genes.

Before applying statistical tests or machine learning models, researchers first examine the overall distribution of expression values.

Descriptive statistics help answer questions such as:

- What is the average expression level?
- Which genes show extremely high expression?
- How variable are the expression values?
- Are there potential outliers?
- Is the dataset balanced?

These statistics provide valuable insight into data quality and biological variability.

Large-scale biological datasets often contain thousands of genes.

Before applying statistical tests or machine learning models, researchers first examine the overall distribution of expression values.

Descriptive statistics help answer questions such as:

- What is the average expression level?
- Which genes show extremely high expression?
- How variable are the expression values?
- Are there potential outliers?
- Is the dataset balanced?

These statistics provide valuable insight into data quality and biological variability.

In [ ]:
# Display descriptive statistics

df.describe()

       Expression  Chromosome     Log2FC     P_Value  Adjusted_P_Value
count  100.000000  100.000000  100.00000  100.000000        100.000000
mean    14.403200   10.760000    0.21180    0.024662          0.027350
std      5.949693    6.731683    2.30322    0.015135          0.016082
min      5.110000    1.000000   -3.88000    0.000600          0.000700
25%      8.865000    5.000000   -1.66500    0.009675          0.014050
50%     14.280000   10.000000    0.36500    0.024700          0.029200
75%     19.602500   17.000000    2.08500    0.037875          0.041950
max     24.740000   22.000000    3.92000    0.049500          0.050000

# **Understanding the Output**

The `describe()` function automatically calculates summary statistics for all numerical columns in the dataset.

For the **Expression**, **Chromosome**, **Log2FC**, **P_Value**, and **Adjusted_P_Value** columns, Pandas calculates:

- Count
- Mean
- Standard Deviation
- Minimum
- 25th Percentile
- Median (50%)
- 75th Percentile
- Maximum

These values provide an overall summary of the dataset.

# **Explain Every Statistic**

**Count**


Count represents the total number of observations available in a numerical column.

For example,

**Count** = 100

means that expression values are available for all 100 genes.

If the count is smaller than expected, it usually indicates missing values.

# **Mean**

The mean is the average value.

**Formula:**

Mean = Sum of all observations ÷ Number of observations

In gene expression studies, the mean represents the average expression level across all genes.

Researchers often compare mean expression levels between healthy and diseased tissues.

# **Standard Deviation (Std)**

Standard deviation measures variability.

A small standard deviation means most genes have similar expression levels.

A large standard deviation indicates substantial variation between genes.

High variability often suggests biologically interesting genes that may require further investigation.

# **Minimum**

The minimum value represents the lowest observed expression level.

Genes with extremely low expression may be:

- weakly expressed
- inactive
- tissue specific

# **Maximum**

The maximum value represents the highest observed expression level.

Highly expressed genes often become candidates for:

- biomarkers
- therapeutic targets
- pathway analysis

# **25th Percentile (First Quartile)**

Twenty-five percent of observations fall below this value.

This statistic helps researchers understand the lower range of gene expression.

# **50th Percentile (Median)**

The median is the middle value.

Half of all observations are below the median.

Unlike the mean, the median is not strongly affected by extreme values.

For skewed biological datasets, the median often provides a better estimate of the central tendency.

# **75th Percentile (Third Quartile)**

Seventy-five percent of observations fall below this value.

Genes above this percentile are generally considered relatively highly expressed compared with the rest of the dataset.

In [ ]:
#calculate each statistic individually.

print("Mean Expression:")
print(df["Expression"].mean())

print("\nMedian Expression:")
print(df["Expression"].median())

print("\nStandard Deviation:")
print(df["Expression"].std())

print("\nMinimum Expression:")
print(df["Expression"].min())

print("\nMaximum Expression:")
print(df["Expression"].max())

Mean Expression:
14.403200000000002

Median Expression:
14.28

Standard Deviation:
5.949693121701677

Minimum Expression:
5.11

Maximum Expression:
24.74

# **Output Explanation**

Instead of relying only on `describe()`, Pandas allows researchers to calculate each statistic individually.

This approach is particularly useful when generating automated reports or comparing multiple biological datasets.

In [ ]:
#Calculate the quartiles separately.

print("25th Percentile:")
print(df["Expression"].quantile(0.25))

print("\nMedian:")
print(df["Expression"].quantile(0.50))

print("\n75th Percentile:")
print(df["Expression"].quantile(0.75))

25th Percentile:
8.865

Median:
14.28

75th Percentile:
19.6025

# **Biological Interpretation**

Suppose the output shows:

Mean Expression = 15.8

This indicates that the average normalized expression level across the analyzed LUAD-associated genes is approximately 15.8.

Genes with expression values substantially greater than the mean may represent highly active genes and could be investigated further as potential biomarkers or therapeutic targets.

Similarly, genes with very low expression may represent inactive or tissue-specific genes.

# **Research Note**

Descriptive statistics are one of the first analyses performed after downloading transcriptomic datasets from public repositories such as:

- The Cancer Genome Atlas (TCGA)
- Gene Expression Omnibus (GEO)
- ArrayExpress
- cBioPortal

These statistics provide an overview of the dataset before performing normalization, differential expression analysis, clustering, or machine learning.

In [ ]:
#Let's identify the genes with expression values above the average.

average_expression = df["Expression"].mean()

high_expression = df[df["Expression"] > average_expression]

high_expression

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
1,BRCA1,24.01,LUAD,17,Oncogene,-0.06,0.0059,0.0051,Downregulated
2,EGFR,19.64,LUAD,20,Tumor Suppressor,-2.44,0.0024,0.0043,Downregulated
3,KRAS,16.97,LUAD,4,Tumor Suppressor,1.78,0.0021,0.0351,Upregulated
7,PIK3CA,22.32,LUAD,15,Tumor Suppressor,-2.58,0.0050,0.0042,Downregulated
8,CDK4,17.02,LUAD,11,Tumor Suppressor,3.52,0.0246,0.0043,Upregulated
9,PTEN,19.16,LUAD,4,Tumor Suppressor,3.63,0.0237,0.0493,Upregulated
11,CCND1,24.40,LUAD,7,Tumor Suppressor,-1.04,0.0217,0.0186,Downregulated
12,ERBB2,21.65,LUAD,19,Tumor Suppressor,-3.88,0.0200,0.0407,Downregulated
17,SMAD4,15.50,LUAD,21,Tumor Suppressor,2.82,0.0313,0.0043,Upregulated
20,AKT1,17.24,LUAD,12,Oncogene,2.81,0.0330,0.0213,Upregulated
25,NFKB1,20.70,LUAD,1,Oncogene,1.57,0.0293,0.0235,Upregulated
27,MDM2,15.28,LUAD,13,Oncogene,-3.22,0.0288,0.0060,Downregulated
28,TERT,16.85,LUAD,9,Tumor Suppressor,0.92,0.0195,0.0060,Upregulated
30,ATM,17.15,LUAD,7,Oncogene,-2.88,0.0230,0.0373,Downregulated
33,CHEK2,23.98,LUAD,9,Tumor Suppressor,1.93,0.0194,0.0188,Upregulated
34,BCL2,24.31,LUAD,5,Tumor Suppressor,1.58,0.0481,0.0144,Upregulated
35,BAX,21.17,LUAD,1,Oncogene,1.62,0.0453,0.0434,Upregulated
38,MMP9,18.68,LUAD,12,Oncogene,2.47,0.0051,0.0007,Upregulated
41,TGFB1,14.90,LUAD,9,Tumor Suppressor,3.31,0.0342,0.0446,Upregulated
43,CD274,23.19,LUAD,17,Tumor Suppressor,0.01,0.0160,0.0496,Upregulated
45,LAG3,18.25,LUAD,20,Tumor Suppressor,1.20,0.0013,0.0277,Upregulated
47,IFNG,15.40,LUAD,7,Tumor Suppressor,2.37,0.0142,0.0262,Upregulated
48,GZMB,15.93,LUAD,2,Tumor Suppressor,3.12,0.0060,0.0315,Upregulated
50,SOX2,24.39,LUAD,17,Oncogene,-1.00,0.0315,0.0228,Downregulated
51,NANOG,20.50,LUAD,5,Oncogene,-3.25,0.0439,0.0314,Downregulated
52,POU5F1,23.79,LUAD,17,Oncogene,0.63,0.0368,0.0293,Upregulated
53,VIM,22.90,LUAD,17,Tumor Suppressor,-3.71,0.0402,0.0451,Downregulated
54,EPCAM,16.96,LUAD,17,Tumor Suppressor,-0.28,0.0142,0.0024,Downregulated
55,SNAI1,23.44,LUAD,2,Tumor Suppressor,0.34,0.0090,0.0141,Upregulated
62,FN1,21.57,LUAD,2,Oncogene,-2.98,0.0171,0.0232,Downregulated
65,CXCR4,15.85,LUAD,6,Tumor Suppressor,-2.27,0.0215,0.0040,Downregulated
67,MKI67,21.04,LUAD,11,Tumor Suppressor,-3.32,0.0378,0.0493,Downregulated
69,TOP2A,24.74,LUAD,6,Tumor Suppressor,0.25,0.0451,0.0269,Upregulated
70,GATA3,20.44,LUAD,5,Tumor Suppressor,0.33,0.0253,0.0155,Upregulated
73,AR,21.31,LUAD,6,Tumor Suppressor,3.81,0.0448,0.0082,Upregulated
74,RUNX1,19.14,LUAD,22,Oncogene,0.13,0.0195,0.0456,Upregulated
75,IDH1,19.58,LUAD,11,Oncogene,-1.42,0.0006,0.0411,Downregulated
76,IDH2,20.43,LUAD,16,Oncogene,2.36,0.0453,0.0475,Upregulated
80,RET,22.26,LUAD,6,Tumor Suppressor,-3.80,0.0475,0.0466,Downregulated
81,NTRK1,17.47,LUAD,16,Oncogene,3.70,0.0287,0.0433,Upregulated
86,KEAP1,19.59,LUAD,3,Tumor Suppressor,-2.75,0.0337,0.0494,Downregulated
87,STK11,17.75,LUAD,19,Tumor Suppressor,-2.00,0.0376,0.0076,Downregulated
88,NF1,22.74,LUAD,20,Tumor Suppressor,0.39,0.0396,0.0297,Upregulated
89,NF2,14.44,LUAD,7,Tumor Suppressor,1.72,0.0395,0.0191,Upregulated
91,PALB2,19.26,LUAD,9,Oncogene,-1.76,0.0248,0.0421,Downregulated
92,RAD51,20.22,LUAD,1,Tumor Suppressor,3.64,0.0030,0.0419,Upregulated
93,XRCC1,16.23,LUAD,8,Tumor Suppressor,1.90,0.0275,0.0235,Upregulated
94,MSH2,20.42,LUAD,7,Oncogene,0.43,0.0221,0.0208,Upregulated
95,MSH6,14.88,LUAD,18,Oncogene,0.89,0.0444,0.0137,Upregulated
96,MLH1,15.45,LUAD,8,Tumor Suppressor,-0.64,0.0176,0.0029,Downregulated

# **Explanation**

### **Interpretation**

This code identifies genes whose expression levels are higher than the overall average.

These genes are often prioritized for:

- biomarker discovery
- pathway enrichment analysis
- functional validation
- downstream statistical testing

# **Mini Exercise**

Using the LUAD gene expression dataset:

1. Calculate the average expression level.

2. Calculate the median.

3. Find the highest expression value.

4. Find the lowest expression value.

5. Calculate the standard deviation.

6. Determine how many genes have expression values greater than the average.

Write a short biological interpretation of your findings.

In [ ]:
#Solution
print("Average:", df["Expression"].mean())

print("Median:", df["Expression"].median())

print("Maximum:", df["Expression"].max())

print("Minimum:", df["Expression"].min())

print("Standard Deviation:", df["Expression"].std())

print("\nGenes Above Average:")

print(df[df["Expression"] > df["Expression"].mean()])

Average: 14.403200000000002
Median: 14.28
Maximum: 24.74
Minimum: 5.11
Standard Deviation: 5.949693121701677

Genes Above Average:
      Gene  Expression Cancer_Type  Chromosome         Gene_Type  Log2FC  \
1    BRCA1       24.01        LUAD          17          Oncogene   -0.06
2     EGFR       19.64        LUAD          20  Tumor Suppressor   -2.44
3     KRAS       16.97        LUAD           4  Tumor Suppressor    1.78
7   PIK3CA       22.32        LUAD          15  Tumor Suppressor   -2.58
8     CDK4       17.02        LUAD          11  Tumor Suppressor    3.52
9     PTEN       19.16        LUAD           4  Tumor Suppressor    3.63
11   CCND1       24.40        LUAD           7  Tumor Suppressor   -1.04
12   ERBB2       21.65        LUAD          19  Tumor Suppressor   -3.88
17   SMAD4       15.50        LUAD          21  Tumor Suppressor    2.82
20    AKT1       17.24        LUAD          12          Oncogene    2.81
25   NFKB1       20.70        LUAD           1          Oncogene    1.57
27    MDM2       15.28        LUAD          13          Oncogene   -3.22
28    TERT       16.85        LUAD           9  Tumor Suppressor    0.92
30     ATM       17.15        LUAD           7          Oncogene   -2.88
33   CHEK2       23.98        LUAD           9  Tumor Suppressor    1.93
34    BCL2       24.31        LUAD           5  Tumor Suppressor    1.58
35     BAX       21.17        LUAD           1          Oncogene    1.62
38    MMP9       18.68        LUAD          12          Oncogene    2.47
41   TGFB1       14.90        LUAD           9  Tumor Suppressor    3.31
43   CD274       23.19        LUAD          17  Tumor Suppressor    0.01
45    LAG3       18.25        LUAD          20  Tumor Suppressor    1.20
47    IFNG       15.40        LUAD           7  Tumor Suppressor    2.37
48    GZMB       15.93        LUAD           2  Tumor Suppressor    3.12
50    SOX2       24.39        LUAD          17          Oncogene   -1.00
51   NANOG       20.50        LUAD           5          Oncogene   -3.25
52  POU5F1       23.79        LUAD          17          Oncogene    0.63
53     VIM       22.90        LUAD          17  Tumor Suppressor   -3.71
54   EPCAM       16.96        LUAD          17  Tumor Suppressor   -0.28
55   SNAI1       23.44        LUAD           2  Tumor Suppressor    0.34
62     FN1       21.57        LUAD           2          Oncogene   -2.98
65   CXCR4       15.85        LUAD           6  Tumor Suppressor   -2.27
67   MKI67       21.04        LUAD          11  Tumor Suppressor   -3.32
69   TOP2A       24.74        LUAD           6  Tumor Suppressor    0.25
70   GATA3       20.44        LUAD           5  Tumor Suppressor    0.33
73      AR       21.31        LUAD           6  Tumor Suppressor    3.81
74   RUNX1       19.14        LUAD          22          Oncogene    0.13
75    IDH1       19.58        LUAD          11          Oncogene   -1.42
76    IDH2       20.43        LUAD          16          Oncogene    2.36
80     RET       22.26        LUAD           6  Tumor Suppressor   -3.80
81   NTRK1       17.47        LUAD          16          Oncogene    3.70
86   KEAP1       19.59        LUAD           3  Tumor Suppressor   -2.75
87   STK11       17.75        LUAD          19  Tumor Suppressor   -2.00
88     NF1       22.74        LUAD          20  Tumor Suppressor    0.39
89     NF2       14.44        LUAD           7  Tumor Suppressor    1.72
91   PALB2       19.26        LUAD           9          Oncogene   -1.76
92   RAD51       20.22        LUAD           1  Tumor Suppressor    3.64
93   XRCC1       16.23        LUAD           8  Tumor Suppressor    1.90
94    MSH2       20.42        LUAD           7          Oncogene    0.43
95    MSH6       14.88        LUAD          18          Oncogene    0.89
96    MLH1       15.45        LUAD           8  Tumor Suppressor   -0.64

    P_Value  Adjusted_P_Value         Status
1    0.0059            0.0051  Downregulated
2    0.0024            0.0043  Downregulated
3    0.0021            0.0351    Upregulated
7    0.0050            0.0042  Downregulated
8    0.0246            0.0043    Upregulated
9    0.0237            0.0493    Upregulated
11   0.0217            0.0186  Downregulated
12   0.0200            0.0407  Downregulated
17   0.0313            0.0043    Upregulated
20   0.0330            0.0213    Upregulated
25   0.0293            0.0235    Upregulated
27   0.0288            0.0060  Downregulated
28   0.0195            0.0060    Upregulated
30   0.0230            0.0373  Downregulated
33   0.0194            0.0188    Upregulated
34   0.0481            0.0144    Upregulated
35   0.0453            0.0434    Upregulated
38   0.0051            0.0007    Upregulated
41   0.0342            0.0446    Upregulated
43   0.0160            0.0496    Upregulated
45   0.0013            0.0277    Upregulated
47   0.0142            0.0262    Upregulated
48   0.0060            0.0315    Upregulated
50   0.0315            0.0228  Downregulated
51   0.0439            0.0314  Downregulated
52   0.0368            0.0293    Upregulated
53   0.0402            0.0451  Downregulated
54   0.0142            0.0024  Downregulated
55   0.0090            0.0141    Upregulated
62   0.0171            0.0232  Downregulated
65   0.0215            0.0040  Downregulated
67   0.0378            0.0493  Downregulated
69   0.0451            0.0269    Upregulated
70   0.0253            0.0155    Upregulated
73   0.0448            0.0082    Upregulated
74   0.0195            0.0456    Upregulated
75   0.0006            0.0411  Downregulated
76   0.0453            0.0475    Upregulated
80   0.0475            0.0466  Downregulated
81   0.0287            0.0433    Upregulated
86   0.0337            0.0494  Downregulated
87   0.0376            0.0076  Downregulated
88   0.0396            0.0297    Upregulated
89   0.0395            0.0191    Upregulated
91   0.0248            0.0421  Downregulated
92   0.0030            0.0419    Upregulated
93   0.0275            0.0235    Upregulated
94   0.0221            0.0208    Upregulated
95   0.0444            0.0137    Upregulated
96   0.0176            0.0029  Downregulated

# **Research Reflection**

During my undergraduate dissertation on transcriptome-based analysis of competing endogenous RNA (ceRNA) networks in lung adenocarcinoma, descriptive statistics would have provided an efficient way to summarize large gene expression datasets before downstream analyses. Instead of manually inspecting expression values, statistical summaries generated using Pandas allow researchers to quickly identify overall trends, highly expressed genes, and potential outliers. These foundational exploratory analyses improve data quality assessment and support more informed biological interpretation.

# **Key Takeaways**

- Used `describe()` to summarize numerical variables.
- Calculated descriptive statistics individually using Pandas functions.
- Learned the biological interpretation of mean, median, variability, and quartiles.
- Identified genes with expression values above the average.
- Understood the importance of descriptive statistics in transcriptomic research.

# **Part 10-C Summary**

In this section, I learned how to summarize numerical variables using Pandas. I explored descriptive statistics such as the mean, median, standard deviation, minimum, maximum, and quartiles to better understand the distribution of gene expression values. These statistical summaries are fundamental components of exploratory data analysis and help researchers evaluate biological datasets before conducting advanced analyses such as differential gene expression, clustering, or predictive modeling.

# **Part- 10D (Section 1) - Filtering and Sorting Biological Data**
After exploring the LUAD gene expression dataset and understanding its statistical properties, researchers often focus on identifying biologically meaningful subsets of genes.

Instead of analyzing all genes simultaneously, computational biologists apply filtering techniques to select genes that satisfy specific biological or statistical criteria.

**Filtering enables researchers to:**

- Identify highly expressed genes
- Detect significantly upregulated genes
- Detect significantly downregulated genes
- Separate oncogenes from tumor suppressor genes
- Select statistically significant genes
- Prepare datasets for downstream analyses such as pathway enrichment, clustering, survival analysis, and machine learning.

In this section, we will learn how Pandas enables efficient filtering and sorting of transcriptomic datasets.

# **Biological Importance**

**Why Filtering is Important in Transcriptomics**?

A typical RNA-Seq experiment measures the expression of more than 20,000 genes.

However, only a relatively small subset of these genes is biologically relevant to a particular disease.

Researchers therefore apply filtering criteria to reduce the dataset and focus on genes that show meaningful biological changes.

Filtering helps researchers:

- Discover biomarkers
- Identify therapeutic targets
- Investigate disease mechanisms
- Reduce computational complexity
- Improve machine learning performance
- Focus on biologically relevant genes

This process is one of the most important stages of exploratory transcriptomic analysis.

In [ ]:
#Section 10D.1
#Filtering Highly Expressed Genes
# Display genes with expression values greater than 18

#high_expression = df[df["Expression"] > 18]

#high_expression

# **Explanation**

**Understanding the Filter**

The expression

```python
df["Expression"] > 18
```

creates a logical condition.

Pandas checks every row in the dataset.

If the expression value is greater than 18,

the row is returned.

Otherwise,

the row is ignored.

This technique is called **Boolean Indexing**, one of the most commonly used filtering methods in Pandas.

# **Biological Interpretation**

Genes with high expression levels are often biologically active.

Highly expressed genes may represent:

- Oncogenes
- Biomarkers
- Drug targets
- Highly active signaling molecules

These genes are frequently prioritized for downstream experimental validation and functional studies.

# **Section 10D.2**

**Filtering Upregulated Genes**


The Log₂ Fold Change (Log2FC) measures the magnitude of change in gene expression between two biological conditions.

Positive Log2FC values indicate increased expression in disease samples.

Negative Log2FC values indicate decreased expression.

In [ ]:
#upregulated = df[df["Log2FC"] > 1]

#upregulated

# **Explanation**

Genes with Log₂ Fold Change > 1 show at least a two-fold increase in expression relative to the comparison group.

These genes are considered significantly upregulated and may contribute to disease progression or altered cellular functions.

# **Biological Importance**

Upregulated genes are commonly investigated because they may:

- Promote tumor growth
- Increase cell proliferation
- Enhance angiogenesis
- Contribute to metastasis
- Activate oncogenic signaling pathways

Many cancer biomarkers originate from highly upregulated genes.

# **Section 10D.3**

**Filtering Downregulated Genes**

In [ ]:
#downregulated = df[df["Log2FC"] < -1]

#downregulated

# **Explanation**

Negative Log₂ Fold Change values indicate decreased expression.

Genes with

Log₂ Fold Change < -1

are commonly classified as downregulated genes.

These genes may have lost biological activity in cancer tissues.

# **Biological Interpretation**

Downregulated genes frequently include:

- Tumor suppressor genes
- DNA repair genes
- Cell cycle regulators
- Apoptosis-related genes

Reduced expression of these genes can contribute to cancer development.

# **Section 10D.4**

**Selecting Oncogenes**

In [ ]:
#oncogenes = df[df["Gene_Type"] == "Oncogene"]

#oncogenes

# **Explanation**

**Understanding the Filter**

This command selects only genes whose

Gene_Type

is equal to

"Oncogene".

The double equal sign (==) is the comparison operator used to check equality in Python.

# **Biological Importance**

Oncogenes are genes that promote cell growth and division.

When mutated or overexpressed, oncogenes can drive tumor initiation and progression.

Examples include:

- EGFR
- KRAS
- MYC
- ALK
- BRAF

Many modern targeted cancer therapies are designed against oncogene products.

# **Section 10D.5**

**Selecting Tumor Suppressor Genes**

In [ ]:
#tumor_suppressors = df[df["Gene_Type"] == "Tumor Suppressor"]

#tumor_suppressors

# **Explanation**

This filter selects genes classified as tumor suppressors.

Tumor suppressor genes normally prevent uncontrolled cell growth.

Loss of function or reduced expression of these genes is a common feature of many cancers.

# **Biological Importance**

Tumor suppressor genes regulate:

- Cell cycle progression
- DNA repair
- Apoptosis
- Genomic stability

Examples include:

- TP53
- BRCA1
- PTEN
- RB1
- APC

These genes are among the most extensively studied genes in cancer biology.

# **Mini Exercise**

Using the LUAD gene expression dataset:

1. Display genes with Expression > 20.

2. Display genes with Log₂FC > 2.

3. Display genes with Log₂FC < -2.

4. Display all Oncogenes.

5. Display all Tumor Suppressor genes.

6. Compare the number of genes in each category.

Write a short biological interpretation of your findings.

In [ ]:
#print("Genes with Expression > 20")

#display(df[df["Expression"] > 20])

print("\nUpregulated Genes (Log2FC > 2)")

#display(df[df["Log2FC"] > 2])

print("\nDownregulated Genes (Log2FC < -2)")

#display(df[df["Log2FC"] < -2])

print("\nOncogenes")

#display(df[df["Gene_Type"] == "Oncogene"])

print("\nTumor Suppressor Genes")

#display(df[df["Gene_Type"] == "Tumor Suppressor"])

Upregulated Genes (Log2FC > 2)

Downregulated Genes (Log2FC < -2)

Oncogenes

Tumor Suppressor Genes

# **Part 10D (Section 2) - Sorting and Ranking Genes for Transcriptomic Analysis**

After filtering biologically relevant genes, researchers often rank genes according to their biological importance.

Sorting allows researchers to identify:

- Highly expressed genes
- Strongly upregulated genes
- Strongly downregulated genes
- Statistically significant genes
- Candidate biomarkers

Instead of manually searching through hundreds or thousands of genes, Pandas enables rapid ranking using a single command.

This step is routinely performed during transcriptomic and differential gene expression analyses.

# **Biological Importance**

 **Why Sorting is bold text Important?**

RNA-Seq datasets usually contain thousands of genes.

Researchers often want to answer questions such as:

• Which genes have the highest expression?

• Which genes show the largest increase in expression?

• Which genes are most statistically significant?

• Which genes should be investigated first?

Sorting allows researchers to prioritize genes for downstream biological analyses and experimental validation.

# **Section 10D.6**

**Sorting by Expression Level**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd
import numpy as np

np.random.seed(42)

genes = [
    "TP53","BRCA1","EGFR","KRAS","MYC","ALK","BRAF","PIK3CA","CDK4","PTEN",
    "RB1","CCND1","ERBB2","MET","FGFR1","VEGFA","CDH1","SMAD4","APC","NRAS",
    "AKT1","MTOR","NOTCH1","JAK2","STAT3","NFKB1","HIF1A","MDM2","TERT","CDKN2A",
    "ATM","ATR","CHEK1","CHEK2","BCL2","BAX","CASP3","FAS","MMP9","CXCL8",
    "IL6","TGFB1","PDCD1","CD274","CTLA4","LAG3","TIGIT","IFNG","GZMB","PRF1",
    "SOX2","NANOG","POU5F1","VIM","EPCAM","SNAI1","TWIST1","ZEB1","MUC1","KRT18",
    "KRT19","COL1A1","FN1","ITGA6","ITGB1","CXCR4","CCR7","MKI67","PCNA","TOP2A",
    "GATA3","FOXA1","ESR1","AR","RUNX1","IDH1","IDH2","FLT3","KIT","ROS1",
    "RET","NTRK1","NTRK2","NTRK3","SMARCA4","ARID1A","KEAP1","STK11","NF1","NF2",
    "BRIP1","PALB2","RAD51","XRCC1","MSH2","MSH6","MLH1","PMS2","POLE","POLD1"
]

n = len(genes)

df = pd.DataFrame({
    "Gene": genes,
    "Expression": np.round(np.random.uniform(5,25,n),2),
    "Cancer_Type":["LUAD"]*n,
    "Chromosome":np.random.randint(1,23,n),
    "Gene_Type":np.random.choice(
        ["Oncogene","Tumor Suppressor"],n),
    "Log2FC":np.round(np.random.uniform(-4,4,n),2),
    "P_Value":np.round(np.random.uniform(0.0001,0.05,n),4),
    "Adjusted_P_Value":np.round(np.random.uniform(0.0001,0.05,n),4)
})

df["Status"]=np.where(
    df["Log2FC"]>0,
    "Upregulated",
    "Downregulated"
)

df.to_csv("LUAD_Gene_Expression_Dataset.csv",index=False)

print("Dataset created successfully!")

Dataset created successfully!

In [ ]:
df = pd.read_csv("LUAD_Gene_Expression_Dataset.csv")

In [ ]:
df.head()

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
0,TP53,12.49,LUAD,7,Oncogene,0.62,0.0008,0.0309,Upregulated
1,BRCA1,24.01,LUAD,17,Oncogene,-0.06,0.0059,0.0051,Downregulated
2,EGFR,19.64,LUAD,20,Tumor Suppressor,-2.44,0.0024,0.0043,Downregulated
3,KRAS,16.97,LUAD,4,Tumor Suppressor,1.78,0.0021,0.0351,Upregulated
4,MYC,8.12,LUAD,5,Oncogene,-1.75,0.0428,0.0037,Downregulated

In [ ]:
expression_sorted = df.sort_values(
    by="Expression",
    ascending=False
)

expression_sorted.head(10)

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
69,TOP2A,24.74,LUAD,6,Tumor Suppressor,0.25,0.0451,0.0269,Upregulated
11,CCND1,24.40,LUAD,7,Tumor Suppressor,-1.04,0.0217,0.0186,Downregulated
50,SOX2,24.39,LUAD,17,Oncogene,-1.00,0.0315,0.0228,Downregulated
34,BCL2,24.31,LUAD,5,Tumor Suppressor,1.58,0.0481,0.0144,Upregulated
1,BRCA1,24.01,LUAD,17,Oncogene,-0.06,0.0059,0.0051,Downregulated
33,CHEK2,23.98,LUAD,9,Tumor Suppressor,1.93,0.0194,0.0188,Upregulated
52,POU5F1,23.79,LUAD,17,Oncogene,0.63,0.0368,0.0293,Upregulated
55,SNAI1,23.44,LUAD,2,Tumor Suppressor,0.34,0.0090,0.0141,Upregulated
43,CD274,23.19,LUAD,17,Tumor Suppressor,0.01,0.0160,0.0496,Upregulated
53,VIM,22.90,LUAD,17,Tumor Suppressor,-3.71,0.0402,0.0451,Downregulated

# **Understanding sort_values()**

The function

```python
sort_values()
```

arranges the rows according to the selected column.

In this example,

```python
ascending=False
```

means:

Highest expression → Lowest expression

If

```python
ascending=True
```

the genes would be arranged from lowest to highest expression.

# **Biological Interpretation**

Highly expressed genes are frequently investigated because they may represent:

- Cancer biomarkers
- Drug targets
- Highly active signaling molecules
- Genes involved in tumor progression

Ranking genes by expression is often the first step before pathway enrichment or functional analysis.

# **Section 10D.7**

**Ranking by Log₂ Fold Change**

In [ ]:
log2fc_sorted = df.sort_values(
    by="Log2FC",
    ascending=False
)

log2fc_sorted

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
29,CDKN2A,5.93,LUAD,3,Tumor Suppressor,3.92,0.0322,0.0325,Upregulated
73,AR,21.31,LUAD,6,Tumor Suppressor,3.81,0.0448,0.0082,Upregulated
15,VEGFA,8.67,LUAD,10,Oncogene,3.73,0.0024,0.0377,Upregulated
16,CDH1,11.08,LUAD,13,Tumor Suppressor,3.71,0.0188,0.0189,Upregulated
81,NTRK1,17.47,LUAD,16,Oncogene,3.70,0.0287,0.0433,Upregulated
...,...,...,...,...,...,...,...,...,...
53,VIM,22.90,LUAD,17,Tumor Suppressor,-3.71,0.0402,0.0451,Downregulated
58,MUC1,5.90,LUAD,5,Tumor Suppressor,-3.76,0.0495,0.0228,Downregulated
80,RET,22.26,LUAD,6,Tumor Suppressor,-3.80,0.0475,0.0466,Downregulated
5,ALK,8.12,LUAD,7,Oncogene,-3.81,0.0352,0.0411,Downregulated
12,ERBB2,21.65,LUAD,19,Tumor Suppressor,-3.88,0.0200,0.0407,Downregulated

# **Explanation**

**Understanding Log₂ Fold Change Ranking**

Log₂ Fold Change represents the magnitude of expression change between two biological conditions.

Sorting genes by Log₂ Fold Change identifies those with the greatest increase in expression.

Genes at the top of the table are the most strongly upregulated.

# **Biological Interpretation**

Genes with high positive Log₂ Fold Change values may represent:

- Activated oncogenes
- Disease-associated pathways
- Therapeutic targets

Researchers frequently prioritize these genes for validation experiments.

# **Section 10D.8 -Sorting by Adjusted p-value**
 **Why Adjusted p-values Matter**?

During RNA-Seq experiments, thousands of genes are tested simultaneously.

Testing many genes increases the chance of false-positive results.

Therefore, researchers adjust p-values using multiple testing correction methods such as the False Discovery Rate (FDR).

Genes with smaller adjusted p-values are generally considered more statistically reliable.

In [ ]:
import pandas as pd
import numpy as np

np.random.seed(42)

genes = [
    "TP53","BRCA1","EGFR","KRAS","MYC","ALK","BRAF","PIK3CA","CDK4","PTEN",
    "RB1","CCND1","ERBB2","MET","FGFR1","VEGFA","CDH1","SMAD4","APC","NRAS",
    "AKT1","MTOR","NOTCH1","JAK2","STAT3","NFKB1","HIF1A","MDM2","TERT","CDKN2A",
    "ATM","ATR","CHEK1","CHEK2","BCL2","BAX","CASP3","FAS","MMP9","CXCL8",
    "IL6","TGFB1","PDCD1","CD274","CTLA4","LAG3","TIGIT","IFNG","GZMB","PRF1",
    "SOX2","NANOG","POU5F1","VIM","EPCAM","SNAI1","TWIST1","ZEB1","MUC1","KRT18",
    "KRT19","COL1A1","FN1","ITGA6","ITGB1","CXCR4","CCR7","MKI67","PCNA","TOP2A",
    "GATA3","FOXA1","ESR1","AR","RUNX1","IDH1","IDH2","FLT3","KIT","ROS1",
    "RET","NTRK1","NTRK2","NTRK3","SMARCA4","ARID1A","KEAP1","STK11","NF1","NF2",
    "BRIP1","PALB2","RAD51","XRCC1","MSH2","MSH6","MLH1","PMS2","POLE","POLD1"
]

n = len(genes)

df = pd.DataFrame({
    "Gene": genes,
    "Expression": np.round(np.random.uniform(5,25,n),2),
    "Cancer_Type":["LUAD"]*n,
    "Chromosome":np.random.randint(1,23,n),
    "Gene_Type":np.random.choice(
        ["Oncogene","Tumor Suppressor"],n),
    "Log2FC":np.round(np.random.uniform(-4,4,n),2),
    "P_Value":np.round(np.random.uniform(0.0001,0.05,n),4),
    "Adjusted_P_Value":np.round(np.random.uniform(0.0001,0.05,n),4)
})

df["Status"]=np.where(
    df["Log2FC"]>0,
    "Upregulated",
    "Downregulated"
)

df.to_csv("LUAD_Gene_Expression_Dataset.csv",index=False)

print("Dataset created successfully!")

Dataset created successfully!

In [ ]:
significant_genes = df.sort_values(
    by="Adjusted_P_Value"
)

significant_genes

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
24,STAT3,14.12,LUAD,1,Oncogene,3.49,0.0014,0.0007,Upregulated
38,MMP9,18.68,LUAD,12,Oncogene,2.47,0.0051,0.0007,Upregulated
83,NTRK3,6.27,LUAD,20,Tumor Suppressor,1.57,0.0225,0.0014,Upregulated
40,IL6,7.44,LUAD,22,Tumor Suppressor,2.94,0.0048,0.0023,Upregulated
82,NTRK2,11.62,LUAD,3,Oncogene,2.69,0.0316,0.0024,Upregulated
...,...,...,...,...,...,...,...,...,...
9,PTEN,19.16,LUAD,4,Tumor Suppressor,3.63,0.0237,0.0493,Upregulated
67,MKI67,21.04,LUAD,11,Tumor Suppressor,-3.32,0.0378,0.0493,Downregulated
86,KEAP1,19.59,LUAD,3,Tumor Suppressor,-2.75,0.0337,0.0494,Downregulated
43,CD274,23.19,LUAD,17,Tumor Suppressor,0.01,0.0160,0.0496,Upregulated
99,POLD1,7.16,LUAD,18,Oncogene,2.06,0.0381,0.0500,Upregulated

# **Explanation**

 **Interpretation**

The dataset is sorted from

Smallest adjusted p-value

↓

Largest adjusted p-value

Genes appearing near the top are statistically more significant.

Researchers usually investigate these genes first.

# **Biological Interpretation**

Statistically significant genes are more likely to represent genuine biological changes rather than random variation.

These genes often proceed to:

- GO Enrichment Analysis

- KEGG Pathway Analysis

- Survival Analysis

- Experimental Validation

# **Section 10D.9-Selecting Important Columns**

In [ ]:
important_columns = df[[
    "Gene",
    "Expression",
    "Log2FC",
    "Adjusted_P_Value",
    "Status"
]]

important_columns.head()

    Gene  Expression  Log2FC  Adjusted_P_Value         Status
0   TP53       12.49    0.62            0.0309    Upregulated
1  BRCA1       24.01   -0.06            0.0051  Downregulated
2   EGFR       19.64   -2.44            0.0043  Downregulated
3   KRAS       16.97    1.78            0.0351    Upregulated
4    MYC        8.12   -1.75            0.0037  Downregulated

# **Explanation**

 **Why Select Specific Columns?**

Large transcriptomic datasets often contain dozens or hundreds of variables.

Researchers usually extract only the variables relevant to their current analysis.

This simplifies visualization, statistical analysis, and reporting.

# **Section 10D.10-Combining Multiple Filters**

# **Advanced Filtering**

One of the greatest strengths of Pandas is the ability to combine multiple biological conditions.

Researchers rarely filter using a single criterion.

Instead, they identify genes that satisfy several biological requirements simultaneously.

In [ ]:
candidate_genes = df[

    (df["Expression"] > 18) &

    (df["Gene_Type"] == "Oncogene") &

    (df["Adjusted_P_Value"] < 0.01)

]

candidate_genes

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
1,BRCA1,24.01,LUAD,17,Oncogene,-0.06,0.0059,0.0051,Downregulated
38,MMP9,18.68,LUAD,12,Oncogene,2.47,0.0051,0.0007,Upregulated

# **Explanation**

**Understanding Multiple Conditions**

The ampersand (&) represents the logical AND operator.

A gene will be selected only if **all** conditions are satisfied:

* High expression

* Classified as an Oncogene

* Statistically significant

This closely resembles filtering strategies used in real RNA-Seq studies.

# **Biological Interpretation**

Genes satisfying all three criteria are strong candidates for:

- Biomarker discovery

- Functional validation

- Drug development

- Precision medicine studies

Such genes often receive the highest priority during downstream analyses.

# **Research Note**

Filtering and ranking genes according to multiple biological criteria is one of the most common tasks performed after differential expression analysis.

Typical filtering criteria include:

• High Log₂ Fold Change

• Low Adjusted p-value

• High Expression

• Known Oncogene Status

• Biological Pathway Membership

These filtered gene lists become the starting point for pathway enrichment analysis, survival studies, biomarker identification, and machine learning.

# **Advanced Mini Research Exercise**

A laboratory has completed RNA-Seq analysis of Lung Adenocarcinoma samples.

Your task is to identify potential biomarker genes.

Perform the following analyses:

1. Sort genes by highest expression.

2. Identify the top 10 most highly expressed genes.

3. Sort genes by Log₂ Fold Change.

4. Display genes with Log₂FC > 2.

5. Sort genes according to Adjusted p-value.

6. Identify statistically significant oncogenes with:

• Expression > 18

• Log₂FC > 2

• Adjusted p-value < 0.01

Write a short biological interpretation explaining why these genes may represent promising biomarker candidates.

In [ ]:
# Top 10 highest expressed genes
top10_expression = df.sort_values(
    by="Expression",
    ascending=False
).head(10)

display(top10_expression)

# Strongly upregulated genes
display(df[df["Log2FC"] > 2])

# Most statistically significant genes
display(df.sort_values(
    by="Adjusted_P_Value"
).head(10))

# Candidate biomarkers
candidate_biomarkers = df[

    (df["Expression"] > 18) &

    (df["Log2FC"] > 2) &

    (df["Adjusted_P_Value"] < 0.01)

]

display(candidate_biomarkers)

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
69,TOP2A,24.74,LUAD,6,Tumor Suppressor,0.25,0.0451,0.0269,Upregulated
11,CCND1,24.40,LUAD,7,Tumor Suppressor,-1.04,0.0217,0.0186,Downregulated
50,SOX2,24.39,LUAD,17,Oncogene,-1.00,0.0315,0.0228,Downregulated
34,BCL2,24.31,LUAD,5,Tumor Suppressor,1.58,0.0481,0.0144,Upregulated
1,BRCA1,24.01,LUAD,17,Oncogene,-0.06,0.0059,0.0051,Downregulated
33,CHEK2,23.98,LUAD,9,Tumor Suppressor,1.93,0.0194,0.0188,Upregulated
52,POU5F1,23.79,LUAD,17,Oncogene,0.63,0.0368,0.0293,Upregulated
55,SNAI1,23.44,LUAD,2,Tumor Suppressor,0.34,0.0090,0.0141,Upregulated
43,CD274,23.19,LUAD,17,Tumor Suppressor,0.01,0.0160,0.0496,Upregulated
53,VIM,22.90,LUAD,17,Tumor Suppressor,-3.71,0.0402,0.0451,Downregulated

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
8,CDK4,17.02,LUAD,11,Tumor Suppressor,3.52,0.0246,0.0043,Upregulated
9,PTEN,19.16,LUAD,4,Tumor Suppressor,3.63,0.0237,0.0493,Upregulated
10,RB1,5.41,LUAD,13,Oncogene,3.32,0.0087,0.0188,Upregulated
13,MET,9.25,LUAD,22,Oncogene,3.43,0.0308,0.0474,Upregulated
15,VEGFA,8.67,LUAD,10,Oncogene,3.73,0.0024,0.0377,Upregulated
16,CDH1,11.08,LUAD,13,Tumor Suppressor,3.71,0.0188,0.0189,Upregulated
17,SMAD4,15.50,LUAD,21,Tumor Suppressor,2.82,0.0313,0.0043,Upregulated
20,AKT1,17.24,LUAD,12,Oncogene,2.81,0.0330,0.0213,Upregulated
24,STAT3,14.12,LUAD,1,Oncogene,3.49,0.0014,0.0007,Upregulated
29,CDKN2A,5.93,LUAD,3,Tumor Suppressor,3.92,0.0322,0.0325,Upregulated
32,CHEK1,6.30,LUAD,8,Tumor Suppressor,3.02,0.0471,0.0481,Upregulated
38,MMP9,18.68,LUAD,12,Oncogene,2.47,0.0051,0.0007,Upregulated
39,CXCL8,13.80,LUAD,15,Oncogene,2.48,0.0010,0.0485,Upregulated
40,IL6,7.44,LUAD,22,Tumor Suppressor,2.94,0.0048,0.0023,Upregulated
41,TGFB1,14.90,LUAD,9,Tumor Suppressor,3.31,0.0342,0.0446,Upregulated
44,CTLA4,10.18,LUAD,17,Tumor Suppressor,2.39,0.0423,0.0038,Upregulated
47,IFNG,15.40,LUAD,7,Tumor Suppressor,2.37,0.0142,0.0262,Upregulated
48,GZMB,15.93,LUAD,2,Tumor Suppressor,3.12,0.0060,0.0315,Upregulated
60,KRT19,12.77,LUAD,1,Tumor Suppressor,2.58,0.0187,0.0139,Upregulated
64,ITGB1,10.62,LUAD,12,Oncogene,2.16,0.0429,0.0292,Upregulated
73,AR,21.31,LUAD,6,Tumor Suppressor,3.81,0.0448,0.0082,Upregulated
76,IDH2,20.43,LUAD,16,Oncogene,2.36,0.0453,0.0475,Upregulated
81,NTRK1,17.47,LUAD,16,Oncogene,3.70,0.0287,0.0433,Upregulated
82,NTRK2,11.62,LUAD,3,Oncogene,2.69,0.0316,0.0024,Upregulated
92,RAD51,20.22,LUAD,1,Tumor Suppressor,3.64,0.0030,0.0419,Upregulated
99,POLD1,7.16,LUAD,18,Oncogene,2.06,0.0381,0.0500,Upregulated

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
24,STAT3,14.12,LUAD,1,Oncogene,3.49,0.0014,0.0007,Upregulated
38,MMP9,18.68,LUAD,12,Oncogene,2.47,0.0051,0.0007,Upregulated
83,NTRK3,6.27,LUAD,20,Tumor Suppressor,1.57,0.0225,0.0014,Upregulated
40,IL6,7.44,LUAD,22,Tumor Suppressor,2.94,0.0048,0.0023,Upregulated
82,NTRK2,11.62,LUAD,3,Oncogene,2.69,0.0316,0.0024,Upregulated
54,EPCAM,16.96,LUAD,17,Tumor Suppressor,-0.28,0.0142,0.0024,Downregulated
26,HIF1A,8.99,LUAD,20,Oncogene,0.56,0.0470,0.0029,Upregulated
96,MLH1,15.45,LUAD,8,Tumor Suppressor,-0.64,0.0176,0.0029,Downregulated
4,MYC,8.12,LUAD,5,Oncogene,-1.75,0.0428,0.0037,Downregulated
44,CTLA4,10.18,LUAD,17,Tumor Suppressor,2.39,0.0423,0.0038,Upregulated

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
38,MMP9,18.68,LUAD,12,Oncogene,2.47,0.0051,0.0007,Upregulated
73,AR,21.31,LUAD,6,Tumor Suppressor,3.81,0.0448,0.0082,Upregulated

# **Research Reflection**

Filtering and ranking genes are fundamental steps in transcriptomic analysis. Through this exercise, I learned how computational tools can rapidly prioritize biologically meaningful genes based on expression level, fold change, and statistical significance. During my undergraduate research on lung adenocarcinoma, similar strategies were used through web-based bioinformatics platforms. Using Pandas provides a reproducible and programmable approach to perform these analyses independently and prepares me for more advanced computational biology workflows.

# **Part 10D-2 Summary**

In this section, I learned how to rank and prioritize genes using Pandas. By sorting gene expression values, Log₂ Fold Change, and adjusted p-values, I identified biologically important genes that could serve as potential biomarkers or therapeutic targets. I also learned how to combine multiple filtering criteria to simulate the gene selection strategies commonly used in RNA-Seq and cancer genomics studies.

# **Key Takeaways**

- Sorted genes by expression level using `sort_values()`.
- Ranked genes according to Log₂ Fold Change.
- Identified statistically significant genes using adjusted p-values.
- Selected only biologically relevant columns for analysis.
- Combined multiple filtering conditions using Boolean indexing.
- Simulated a real RNA-Seq candidate biomarker selection workflow.

# **Part 10D (Section 3) -Mini Transcriptomics Workflow: LUAD Biomarker Discovery**

 **Part 10D.3 – Mini Transcriptomics Case Study**

In computational biology, filtering and ranking genes are not the final objective.

Instead, these analyses help researchers identify biologically meaningful genes that can be investigated further through laboratory experiments or advanced computational analyses.

In this section, we will simulate a simplified biomarker discovery workflow using the LUAD gene expression dataset.

The goal is to identify genes that are:

• Highly expressed

• Strongly upregulated

• Statistically significant

• Classified as oncogenes

These genes may represent potential biomarkers or therapeutic targets for Lung Adenocarcinoma.

# **Biological Importance**

### Why Biomarker Discovery Matters?

Biomarkers are measurable biological molecules that indicate:

• Disease presence

• Disease progression

• Treatment response

• Patient prognosis

In cancer research, computational analysis is commonly used to identify candidate biomarkers before experimental validation.

Filtering transcriptomic datasets allows researchers to prioritize the most promising genes for further biological investigation.

# **Section 10D.11-Count Gene Categories**

In [ ]:
print("Total Genes:", len(df))

print("\nUpregulated Genes:")
print(len(df[df["Status"]=="Upregulated"]))

print("\nDownregulated Genes:")
print(len(df[df["Status"]=="Downregulated"]))

print("\nOncogenes:")
print(len(df[df["Gene_Type"]=="Oncogene"]))

print("\nTumor Suppressor Genes:")
print(len(df[df["Gene_Type"]=="Tumor Suppressor"]))

Total Genes: 100

Upregulated Genes:
58

Downregulated Genes:
42

Oncogenes:
43

Tumor Suppressor Genes:
57

# **Explanation**

 **Understanding Category Counts**

Before beginning downstream analyses, researchers often summarize the composition of the dataset.

Category counts provide a quick overview of:

- Number of oncogenes
- Number of tumor suppressor genes
- Number of upregulated genes
- Number of downregulated genes

These summaries help researchers understand the biological characteristics of the dataset before more advanced analyse

# **Biological Interpretation**

A predominance of upregulated oncogenes may indicate activation of tumor-promoting pathways.

Conversely, increased numbers of downregulated tumor suppressor genes may suggest disruption of normal cellular regulatory mechanisms.

These observations provide an initial overview of the molecular characteristics of the dataset.

# **Section 10D.12-Export Candidate Biomarkers**

In [ ]:
candidate_biomarkers = df[

    (df["Expression"] > 18) &
    (df["Log2FC"] > 2) &
    (df["Adjusted_P_Value"] < 0.01)

]

candidate_biomarkers

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
38,MMP9,18.68,LUAD,12,Oncogene,2.47,0.0051,0.0007,Upregulated
73,AR,21.31,LUAD,6,Tumor Suppressor,3.81,0.0448,0.0082,Upregulated

In [ ]:
candidate_biomarkers.to_csv(
    "Candidate_Biomarkers_LUAD.csv",
    index=False
)

print("Candidate Biomarker List Saved Successfully!")

Candidate Biomarker List Saved Successfully!

# **Explanation**

**Why Export Filtered Genes?**

Rather than repeatedly filtering the entire dataset, researchers often save biologically important subsets as separate files.

Exporting filtered datasets allows:

- Sharing results with collaborators
- Importing into R or Excel
- Performing pathway enrichment analysis
- Creating publication-quality figures
- Building machine learning datasets

CSV files are the most common exchange format in computational biology.

# **Section 10D.13-Verify Export**

In [ ]:
import os

os.listdir()

['.config',
 'LUAD_Gene_Expression_Dataset.csv',
 'Candidate_Biomarkers_LUAD.csv',
 'sample_data']

# **Explanation**

The exported file

Candidate_Biomarkers_LUAD.csv

should now appear in the working directory.

This confirms that the filtered biomarker list has been successfully created and is ready for downstream analyses.

# **Research Note**

Exporting intermediate results is a standard practice in computational biology.

Large RNA-Seq projects often generate multiple files including:

- Differential expression tables
- Significant gene lists
- Pathway enrichment results
- Clinical annotations
- Machine learning feature matrices

Saving intermediate outputs improves reproducibility and facilitates collaboration among researchers.

# **Mini Research Project**

Imagine you are part of a cancer genomics laboratory studying Lung Adenocarcinoma.

Your objective is to identify potential biomarker genes for future experimental validation.

Using the LUAD dataset:

1. Count the total number of genes.

2. Count upregulated genes.

3. Count downregulated genes.

4. Count oncogenes.

5. Count tumor suppressor genes.

6. Identify highly expressed genes.

7. Identify significantly upregulated genes.

8. Filter candidate biomarkers using:

   • Expression > 18

   • Log₂ Fold Change > 2

   • Adjusted p-value < 0.01

9. Save the candidate biomarker list.

10. Write a biological interpretation of your findings.

In [ ]:
print("Dataset Overview")
print(df.shape)

print("\nGene Categories")
print(df["Gene_Type"].value_counts())

print("\nExpression Status")
print(df["Status"].value_counts())

candidate = df[

    (df["Expression"] > 18) &
    (df["Log2FC"] > 2) &
    (df["Adjusted_P_Value"] < 0.01)

]

print("\nCandidate Biomarkers")

display(candidate)

candidate.to_csv(
    "Candidate_Biomarkers_LUAD.csv",
    index=False
)

Dataset Overview
(100, 9)

Gene Categories
Gene_Type
Tumor Suppressor    57
Oncogene            43
Name: count, dtype: int64

Expression Status
Status
Upregulated      58
Downregulated    42
Name: count, dtype: int64

Candidate Biomarkers

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
38,MMP9,18.68,LUAD,12,Oncogene,2.47,0.0051,0.0007,Upregulated
73,AR,21.31,LUAD,6,Tumor Suppressor,3.81,0.0448,0.0082,Upregulated

# **Research Reflection**

Through this notebook, I learned how computational tools can efficiently prioritize biologically meaningful genes from transcriptomic datasets.

During my undergraduate dissertation on transcriptome-based analysis of competing endogenous RNA (ceRNA) networks associated with lung adenocarcinoma prognosis, I primarily relied on web-based bioinformatics resources for gene exploration. Using Pandas has shown me how similar analyses can be performed programmatically, allowing for greater reproducibility, flexibility, and scalability.

Developing these computational skills strengthens my ability to analyze large-scale biological datasets and prepares me for future research in computational biology, cancer genomics, and biomedical data science.

# **Career Connection**

The filtering and ranking strategies introduced in this notebook are fundamental skills for careers in:

- Computational Biology
- Bioinformatics
- Cancer Genomics
- Biomedical Data Science
- Precision Medicine
- Clinical Genomics
- Drug Discovery
- AI for Healthcare

These techniques are routinely used in research laboratories, biotechnology companies, pharmaceutical industries, and academic institutions to analyze high-throughput biological data and identify candidate biomarkers.

# **Part 10D Summary**

In this section, I learned how to filter, sort, and prioritize genes using Pandas. By combining biological criteria such as expression level, Log₂ Fold Change, adjusted p-value, and gene classification, I simulated a transcriptomic biomarker discovery workflow similar to those used in cancer genomics research.

I also learned how to export filtered datasets for downstream analyses, an essential step in reproducible computational biology workflows.

# **Key Takeaways**

* Applied Boolean indexing to filter biological datasets.

* Sorted genes according to expression level and statistical significance.

* Ranked candidate biomarkers using multiple biological criteria.

* Exported filtered gene lists as CSV files.

* Simulated a simplified LUAD biomarker discovery workflow.

* Learned how computational filtering supports biological interpretation and downstream bioinformatics analyses.

# **Part 10E - Missing Values and Data Cleaning in Biomedical Datasets**
Before performing any statistical analysis or machine learning, researchers must ensure that biological datasets are complete, accurate, and reliable.

Large biomedical datasets often contain missing values due to experimental limitations, sequencing errors, incomplete clinical records, or quality control filtering.

If these missing values are ignored, they can introduce bias into statistical analyses and lead to incorrect biological conclusions.

In this section, we will learn how to identify, interpret, and handle missing values using Pandas while working with our simulated Lung Adenocarcinoma (LUAD) gene expression dataset.

# **Why Missing Values Matter in Computational Biology?**

Missing values are common in biological datasets because experimental techniques are rarely perfect.

Examples include:

- RNA sequencing reads with insufficient coverage.
- Genes filtered out during quality control.
- Missing patient follow-up information.
- Laboratory measurement errors.
- Corrupted sequencing files.
- Failed experiments.
- Clinical information not recorded.

Handling missing values correctly improves the reliability and reproducibility of downstream analyses.

In [ ]:
import pandas as pd
import numpy as np

np.random.seed(42)

genes = [
    "TP53","BRCA1","EGFR","KRAS","MYC","ALK","BRAF","PIK3CA","CDK4","PTEN",
    "RB1","CCND1","ERBB2","MET","FGFR1","VEGFA","CDH1","SMAD4","APC","NRAS",
    "AKT1","MTOR","NOTCH1","JAK2","STAT3","NFKB1","HIF1A","MDM2","TERT","CDKN2A",
    "ATM","ATR","CHEK1","CHEK2","BCL2","BAX","CASP3","FAS","MMP9","CXCL8",
    "IL6","TGFB1","PDCD1","CD274","CTLA4","LAG3","TIGIT","IFNG","GZMB","PRF1",
    "SOX2","NANOG","POU5F1","VIM","EPCAM","SNAI1","TWIST1","ZEB1","MUC1","KRT18",
    "KRT19","COL1A1","FN1","ITGA6","ITGB1","CXCR4","CCR7","MKI67","PCNA","TOP2A",
    "GATA3","FOXA1","ESR1","AR","RUNX1","IDH1","IDH2","FLT3","KIT","ROS1",
    "RET","NTRK1","NTRK2","NTRK3","SMARCA4","ARID1A","KEAP1","STK11","NF1","NF2",
    "BRIP1","PALB2","RAD51","XRCC1","MSH2","MSH6","MLH1","PMS2","POLE","POLD1"
]

n = len(genes)

df = pd.DataFrame({
    "Gene": genes,
    "Expression": np.round(np.random.uniform(5,25,n),2),
    "Cancer_Type":["LUAD"]*n,
    "Chromosome":np.random.randint(1,23,n),
    "Gene_Type":np.random.choice(
        ["Oncogene","Tumor Suppressor"],n),
    "Log2FC":np.round(np.random.uniform(-4,4,n),2),
    "P_Value":np.round(np.random.uniform(0.0001,0.05,n),4),
    "Adjusted_P_Value":np.round(np.random.uniform(0.0001,0.05,n),4)
})

df["Status"]=np.where(
    df["Log2FC"]>0,
    "Upregulated",
    "Downregulated"
)

df.to_csv("LUAD_Gene_Expression_Dataset.csv",index=False)

print("Dataset created successfully!")

Dataset created successfully!

In [ ]:
# Create missing values for demonstration

df.loc[5, "Expression"] = None
df.loc[18, "Adjusted_P_Value"] = None
df.loc[42, "Log2FC"] = None

df.head(20)

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
0,TP53,12.49,LUAD,7,Oncogene,0.62,0.0008,0.0309,Upregulated
1,BRCA1,24.01,LUAD,17,Oncogene,-0.06,0.0059,0.0051,Downregulated
2,EGFR,19.64,LUAD,20,Tumor Suppressor,-2.44,0.0024,0.0043,Downregulated
3,KRAS,16.97,LUAD,4,Tumor Suppressor,1.78,0.0021,0.0351,Upregulated
4,MYC,8.12,LUAD,5,Oncogene,-1.75,0.0428,0.0037,Downregulated
5,ALK,NaN,LUAD,7,Oncogene,-3.81,0.0352,0.0411,Downregulated
6,BRAF,6.16,LUAD,13,Tumor Suppressor,1.16,0.0238,0.0353,Upregulated
7,PIK3CA,22.32,LUAD,15,Tumor Suppressor,-2.58,0.0050,0.0042,Downregulated
8,CDK4,17.02,LUAD,11,Tumor Suppressor,3.52,0.0246,0.0043,Upregulated
9,PTEN,19.16,LUAD,4,Tumor Suppressor,3.63,0.0237,0.0493,Upregulated
10,RB1,5.41,LUAD,13,Oncogene,3.32,0.0087,0.0188,Upregulated
11,CCND1,24.40,LUAD,7,Tumor Suppressor,-1.04,0.0217,0.0186,Downregulated
12,ERBB2,21.65,LUAD,19,Tumor Suppressor,-3.88,0.0200,0.0407,Downregulated
13,MET,9.25,LUAD,22,Oncogene,3.43,0.0308,0.0474,Upregulated
14,FGFR1,8.64,LUAD,2,Tumor Suppressor,-0.57,0.0318,0.0493,Downregulated
15,VEGFA,8.67,LUAD,10,Oncogene,3.73,0.0024,0.0377,Upregulated
16,CDH1,11.08,LUAD,13,Tumor Suppressor,3.71,0.0188,0.0189,Upregulated
17,SMAD4,15.50,LUAD,21,Tumor Suppressor,2.82,0.0313,0.0043,Upregulated
18,APC,13.64,LUAD,6,Tumor Suppressor,-1.64,0.0252,NaN,Downregulated
19,NRAS,10.82,LUAD,12,Oncogene,-0.92,0.0428,0.0280,Downregulated

# **Explanation**

To demonstrate how missing values are handled, we intentionally introduced three missing observations into different columns of the dataset.

In real biological datasets, these missing values occur naturally due to technical limitations rather than being manually inserted.

This simulated example allows us to practice common data-cleaning techniques before working with real RNA-Seq datasets.

In [ ]:
# Detect missing values

df.isnull()

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False

# **Understanding the Output**

The `isnull()` function checks every cell in the dataset.

It returns:

- **True** → the value is missing.
- **False** → the value is present.

Although this output is useful for small datasets, it becomes difficult to interpret when thousands of genes are present. Therefore, researchers usually summarize missing values instead of inspecting every row individually.

In [ ]:
# Count missing values in each column

df.isnull().sum()

Gene                0
Expression          1
Cancer_Type         0
Chromosome          0
Gene_Type           0
Log2FC              1
P_Value             0
Adjusted_P_Value    1
Status              0
dtype: int64

# **Explanation of the Output**

The `sum()` function counts the number of **True** values returned by `isnull()`.

Each number represents the total missing observations in a column.

For example:

- Expression → 1
- Log2FC → 1
- Adjusted_P_Value → 1

This indicates that one observation is missing in each of these variables.

Researchers perform this quality assessment before deciding whether to remove or replace missing values.

In [ ]:
# Display only rows containing missing values

df[df.isnull().any(axis=1)]

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
5,ALK,NaN,LUAD,7,Oncogene,-3.81,0.0352,0.0411,Downregulated
18,APC,13.64,LUAD,6,Tumor Suppressor,-1.64,0.0252,NaN,Downregulated
42,PDCD1,5.69,LUAD,20,Tumor Suppressor,NaN,0.0037,0.0264,Upregulated

# **Why This Is Useful**?

Instead of searching through the entire dataset manually, this command displays only the rows that contain missing values.

This helps researchers quickly identify problematic samples or genes before deciding how to clean the dataset.

## **Biological** **Interpretation**

In transcriptomic studies, missing values may indicate:

- Low sequencing depth
- Failed RNA extraction
- Low-quality sequencing reads
- Filtering during quality control
- Missing clinical annotations

Before continuing the analysis, researchers investigate whether these missing values occurred randomly or are associated with a specific biological factor.

In [ ]:
# Remove rows containing missing values

clean_df = df.dropna()

clean_df.head()

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
0,TP53,12.49,LUAD,7,Oncogene,0.62,0.0008,0.0309,Upregulated
1,BRCA1,24.01,LUAD,17,Oncogene,-0.06,0.0059,0.0051,Downregulated
2,EGFR,19.64,LUAD,20,Tumor Suppressor,-2.44,0.0024,0.0043,Downregulated
3,KRAS,16.97,LUAD,4,Tumor Suppressor,1.78,0.0021,0.0351,Upregulated
4,MYC,8.12,LUAD,5,Oncogene,-1.75,0.0428,0.0037,Downregulated

# **Understanding `dropna()`**

The `dropna()` function removes every row that contains one or more missing values.

This creates a cleaned version of the dataset that can be used for downstream analyses.

However, removing too many rows may reduce statistical power if the dataset contains many missing observations.

In [ ]:
#Compare Dataset Size
print("Original Dataset Shape:", df.shape)

print("Cleaned Dataset Shape:", clean_df.shape)

Original Dataset Shape: (100, 9)
Cleaned Dataset Shape: (97, 9)

# **Interpretation**

Comparing the dataset dimensions before and after cleaning allows researchers to determine how much data was removed.

A small reduction usually has little impact.

A large reduction may indicate poor data quality and should be investigated further.

In [ ]:
# Fill missing Expression values using the mean

df["Expression"] = df["Expression"].fillna(
    df["Expression"].mean()
)

df.head()

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
0,TP53,12.49,LUAD,7,Oncogene,0.62,0.0008,0.0309,Upregulated
1,BRCA1,24.01,LUAD,17,Oncogene,-0.06,0.0059,0.0051,Downregulated
2,EGFR,19.64,LUAD,20,Tumor Suppressor,-2.44,0.0024,0.0043,Downregulated
3,KRAS,16.97,LUAD,4,Tumor Suppressor,1.78,0.0021,0.0351,Upregulated
4,MYC,8.12,LUAD,5,Oncogene,-1.75,0.0428,0.0037,Downregulated

# **Why Use the Mean?**

Replacing missing values with the mean preserves the size of the dataset while maintaining the overall average expression level.

This approach is commonly used when only a few values are missing and the data are approximately normally distributed.

However, excessive imputation should be avoided because it may reduce biological variability.

In [ ]:
# Fill missing Log2FC values using the median

df["Log2FC"] = df["Log2FC"].fillna(
    df["Log2FC"].median()
)

# **Why Use the Median?**

The median is less affected by extreme values than the mean.

For skewed biological datasets, the median often provides a more robust estimate when replacing missing observations.

In [ ]:
# Replace missing adjusted p-values

df["Adjusted_P_Value"] = df["Adjusted_P_Value"].fillna(0.05)

# **Biological Interpretation**

Adjusted p-values estimate the statistical significance of differential expression after correcting for multiple hypothesis testing.

Assigning a conservative value such as **0.05** prevents missing observations from being incorrectly interpreted as statistically significant.

In real research projects, the method used for replacing missing p-values depends on the experimental design and statistical analysis pipeline.

In [ ]:
# Confirm that all missing values have been handled

df.isnull().sum()

Gene                0
Expression          0
Cancer_Type         0
Chromosome          0
Gene_Type           0
Log2FC              0
P_Value             0
Adjusted_P_Value    0
Status              0
dtype: int64

# **Interpretation**

All columns should now contain **zero missing values**, indicating that the dataset has been successfully cleaned and is ready for downstream analyses such as filtering, visualization, statistical testing, or machine learning.

# **Mini Research Exercise**

A research laboratory downloaded an RNA-Seq dataset from lung adenocarcinoma patients.

Your tasks are:

1. Detect missing values.
2. Count missing values in each column.
3. Display only rows containing missing values.
4. Remove incomplete rows.
5. Replace missing expression values with the mean.
6. Replace missing Log₂ Fold Change values with the median.
7. Verify that the cleaned dataset contains no missing values.

Finally, write a short biological interpretation describing why proper handling of missing values is essential before performing transcriptomic analyses.
✅ Solution

In [ ]:
# Detect missing values
print(df.isnull().sum())

# Display rows with missing values
print(df[df.isnull().any(axis=1)])

# Remove missing rows
clean_df = df.dropna()

# Replace missing values
df["Expression"] = df["Expression"].fillna(df["Expression"].mean())
df["Log2FC"] = df["Log2FC"].fillna(df["Log2FC"].median())
df["Adjusted_P_Value"] = df["Adjusted_P_Value"].fillna(0.05)

# Verify
print(df.isnull().sum())

Gene                0
Expression          0
Cancer_Type         0
Chromosome          0
Gene_Type           0
Log2FC              0
P_Value             0
Adjusted_P_Value    0
Status              0
dtype: int64
Empty DataFrame
Columns: [Gene, Expression, Cancer_Type, Chromosome, Gene_Type, Log2FC, P_Value, Adjusted_P_Value, Status]
Index: []
Gene                0
Expression          0
Cancer_Type         0
Chromosome          0
Gene_Type           0
Log2FC              0
P_Value             0
Adjusted_P_Value    0
Status              0
dtype: int64

# **Research Challenge**

Imagine you are analyzing an RNA-Seq dataset containing 20,000 genes.

Approximately 30% of the genes contain missing expression values.

Would you:

- Remove all incomplete genes?
- Replace the missing values?
- Re-sequence the samples?
- Apply another quality control strategy?

Discuss the advantages and disadvantages of each approach based on biological and statistical considerations

# **Research Reflection**

During my undergraduate dissertation on transcriptome-based analysis of competing endogenous RNA (ceRNA) networks in lung adenocarcinoma, I primarily analyzed processed gene expression datasets obtained from public bioinformatics resources. Through this notebook, I learned how missing values can be identified, quantified, and appropriately handled using Pandas before conducting downstream analyses. Developing these data-cleaning skills strengthens my ability to work independently with large transcriptomic datasets and supports more reliable computational biology research.

# **Part 10E- Summary**

In this section, I learned how to identify and handle missing values in a simulated lung adenocarcinoma gene expression dataset using Pandas. I explored multiple strategies for detecting incomplete observations, removing problematic records, and replacing missing values with appropriate statistical estimates. These data-cleaning techniques are fundamental steps in computational biology workflows and help ensure that downstream statistical analyses, visualization, and machine learning models are based on reliable and biologically meaningful datasets.

##  **Key Takeaways**

- Learned how to detect missing values using `isnull()`.
- Counted missing observations in each variable.
- Displayed rows containing incomplete data.
- Removed incomplete observations using `dropna()`.
- Replaced missing values using the mean, median, and fixed constants.
- Understood the biological importance of data cleaning before statistical analysis.
- Prepared a clean LUAD dataset for downstream transcriptomic analyses.

# **Part 10F - Mini RNA-Seq Exploratory Analysis of a Lung Adenocarcinoma (LUAD) Gene Expression Dataset**
In previous sections, we learned how to:

* Load biological datasets

* Explore their structure

* Calculate descriptive statistics

* Filter biologically relevant genes

* Handle missing values

These are the essential preprocessing steps performed before conducting biological interpretation.

In this section, we will combine these individual skills into a complete exploratory analysis of a simulated Lung Adenocarcinoma (LUAD) RNA-Seq dataset.

Rather than focusing on isolated Pandas functions, we will follow a research-oriented workflow similar to those used in transcriptomics laboratories.

By the end of this section, we will have identified candidate genes for further investigation based on their expression levels, fold changes, and statistical significance.

# **Why Exploratory Data Analysis Matters?**

Before applying advanced bioinformatics techniques such as:

- Differential Gene Expression Analysis
- Gene Ontology (GO) Enrichment
- KEGG Pathway Analysis
- Machine Learning
- Biomarker Discovery

researchers first perform Exploratory Data Analysis (EDA).

EDA helps answer questions such as:

- Which genes are highly expressed?
- Which genes are significantly upregulated?
- Are expression values normally distributed?
- Are statistically significant genes present?
- Which genes should be prioritized for downstream analysis?

Exploratory analysis reduces errors and provides biological insight before more complex analyses.

# **Research Workflow**

Today's analysis follows a simplified RNA-Seq pipeline:

```
Raw Gene Expression Dataset
          │
          ▼
Load Dataset
          │
          ▼
Explore Dataset
          │
          ▼
Clean Missing Values
          │
          ▼
Filter Significant Genes
          │
          ▼
Rank Candidate Biomarkers
          │
          ▼
Interpret Biological Results
          │
          ▼
Prepare for Visualization (Day 11)
```

In [ ]:
# Display first 10 genes

df.head(10)

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
0,TP53,12.490000,LUAD,7,Oncogene,0.62,0.0008,0.0309,Upregulated
1,BRCA1,24.010000,LUAD,17,Oncogene,-0.06,0.0059,0.0051,Downregulated
2,EGFR,19.640000,LUAD,20,Tumor Suppressor,-2.44,0.0024,0.0043,Downregulated
3,KRAS,16.970000,LUAD,4,Tumor Suppressor,1.78,0.0021,0.0351,Upregulated
4,MYC,8.120000,LUAD,5,Oncogene,-1.75,0.0428,0.0037,Downregulated
5,ALK,14.466667,LUAD,7,Oncogene,-3.81,0.0352,0.0411,Downregulated
6,BRAF,6.160000,LUAD,13,Tumor Suppressor,1.16,0.0238,0.0353,Upregulated
7,PIK3CA,22.320000,LUAD,15,Tumor Suppressor,-2.58,0.0050,0.0042,Downregulated
8,CDK4,17.020000,LUAD,11,Tumor Suppressor,3.52,0.0246,0.0043,Upregulated
9,PTEN,19.160000,LUAD,4,Tumor Suppressor,3.63,0.0237,0.0493,Upregulated

# **Interpretation**

This provides an overview of the LUAD gene expression dataset.

Each row represents one cancer-associated gene.

Each column provides different biological information including:

- Gene Symbol
- Expression Level
- Gene Type
- Log₂ Fold Change
- P-value
- Adjusted P-value
- Regulation Status

Together, these variables describe the molecular characteristics of each gene.

In [ ]:
# Count gene regulation status

df["Status"].value_counts()

Status
Upregulated      58
Downregulated    42
Name: count, dtype: int64

# **Interpretation**

The Status column categorizes genes as:

• Upregulated

or

• Downregulated

Upregulated genes generally show increased expression in cancer tissues.

Downregulated genes show reduced expression.

This classification forms the basis of differential gene expression studies.

In [ ]:
status_percentage = (
    df["Status"]
      .value_counts(normalize=True)
      *100
)

status_percentage

Status
Upregulated      58.0
Downregulated    42.0
Name: proportion, dtype: float64

# **Biological Interpretation**

Calculating percentages helps summarize the molecular profile of the dataset.

For example,

if 62% of genes are Upregulated,

this indicates that many cancer-associated genes are transcriptionally activated.

Such activation may reflect uncontrolled cell proliferation or oncogenic signaling pathways.

In [ ]:
#Number of Oncogenes and Tumor Suppressor Genes
df["Gene_Type"].value_counts()

Gene_Type
Tumor Suppressor    57
Oncogene            43
Name: count, dtype: int64

# **Interpretation**

Genes are broadly classified into two biological categories.

**Oncogenes**

Genes whose activation promotes tumor growth.

Examples include:

- EGFR
- KRAS
- MYC
- ALK

**Tumor Suppressor Genes**

Genes that normally inhibit uncontrolled cell division.

Examples include:

- TP53
- PTEN
- RB1
- BRCA1

Understanding this balance is essential in cancer biology.

In [ ]:
highest_gene = df.loc[
    df["Expression"].idxmax()
]

highest_gene

Gene                           TOP2A
Expression                     24.74
Cancer_Type                     LUAD
Chromosome                         6
Gene_Type           Tumor Suppressor
Log2FC                          0.25
P_Value                       0.0451
Adjusted_P_Value              0.0269
Status                   Upregulated
Name: 69, dtype: object

# **Interpretation**

The highest expressed gene represents the gene with the greatest normalized expression value in the dataset.

Genes with extremely high expression are often investigated as:

- Diagnostic biomarkers
- Therapeutic targets
- Driver genes
- Prognostic markers

These genes frequently become candidates for functional validation experiments.

In [ ]:
#Lowest Expressed Gene
lowest_gene = df.loc[
    df["Expression"].idxmin()
]

lowest_gene

Gene                            ESR1
Expression                      5.11
Cancer_Type                     LUAD
Chromosome                         2
Gene_Type           Tumor Suppressor
Log2FC                          1.81
P_Value                       0.0161
Adjusted_P_Value              0.0343
Status                   Upregulated
Name: 72, dtype: object

# **Interpretation**

Genes with very low expression may be:

- inactive

- tissue specific

- weakly expressed

or

- biologically repressed.

Although less obvious than highly expressed genes, they may still provide important biological information.

In [ ]:
#Significant Genes
significant_genes = df[
    df["Adjusted_P_Value"] < 0.05
]

significant_genes.head(15)

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
0,TP53,12.490000,LUAD,7,Oncogene,0.62,0.0008,0.0309,Upregulated
1,BRCA1,24.010000,LUAD,17,Oncogene,-0.06,0.0059,0.0051,Downregulated
2,EGFR,19.640000,LUAD,20,Tumor Suppressor,-2.44,0.0024,0.0043,Downregulated
3,KRAS,16.970000,LUAD,4,Tumor Suppressor,1.78,0.0021,0.0351,Upregulated
4,MYC,8.120000,LUAD,5,Oncogene,-1.75,0.0428,0.0037,Downregulated
5,ALK,14.466667,LUAD,7,Oncogene,-3.81,0.0352,0.0411,Downregulated
6,BRAF,6.160000,LUAD,13,Tumor Suppressor,1.16,0.0238,0.0353,Upregulated
7,PIK3CA,22.320000,LUAD,15,Tumor Suppressor,-2.58,0.0050,0.0042,Downregulated
8,CDK4,17.020000,LUAD,11,Tumor Suppressor,3.52,0.0246,0.0043,Upregulated
9,PTEN,19.160000,LUAD,4,Tumor Suppressor,3.63,0.0237,0.0493,Upregulated
10,RB1,5.410000,LUAD,13,Oncogene,3.32,0.0087,0.0188,Upregulated
11,CCND1,24.400000,LUAD,7,Tumor Suppressor,-1.04,0.0217,0.0186,Downregulated
12,ERBB2,21.650000,LUAD,19,Tumor Suppressor,-3.88,0.0200,0.0407,Downregulated
13,MET,9.250000,LUAD,22,Oncogene,3.43,0.0308,0.0474,Upregulated
14,FGFR1,8.640000,LUAD,2,Tumor Suppressor,-0.57,0.0318,0.0493,Downregulated

## **Explanation**

 **Why Adjusted P-values?**

Thousands of genes are tested simultaneously during RNA-Seq analysis.

Multiple statistical tests increase the probability of false positive results.

Adjusted p-values correct for this problem.

Genes with Adjusted P-value < 0.05 are generally considered statistically significant.

These genes become candidates for downstream biological interpretation.

In [ ]:
#Count Significant Genes
print("Number of Significant Genes:")

print(len(significant_genes))

Number of Significant Genes:
98

In [ ]:
#Candidate Biomarkers
candidate_biomarkers = df[
    (df["Expression"]>18) &
    (df["Adjusted_P_Value"]<0.05)
]

candidate_biomarkers

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
1,BRCA1,24.01,LUAD,17,Oncogene,-0.06,0.0059,0.0051,Downregulated
2,EGFR,19.64,LUAD,20,Tumor Suppressor,-2.44,0.0024,0.0043,Downregulated
7,PIK3CA,22.32,LUAD,15,Tumor Suppressor,-2.58,0.0050,0.0042,Downregulated
9,PTEN,19.16,LUAD,4,Tumor Suppressor,3.63,0.0237,0.0493,Upregulated
11,CCND1,24.40,LUAD,7,Tumor Suppressor,-1.04,0.0217,0.0186,Downregulated
12,ERBB2,21.65,LUAD,19,Tumor Suppressor,-3.88,0.0200,0.0407,Downregulated
25,NFKB1,20.70,LUAD,1,Oncogene,1.57,0.0293,0.0235,Upregulated
33,CHEK2,23.98,LUAD,9,Tumor Suppressor,1.93,0.0194,0.0188,Upregulated
34,BCL2,24.31,LUAD,5,Tumor Suppressor,1.58,0.0481,0.0144,Upregulated
35,BAX,21.17,LUAD,1,Oncogene,1.62,0.0453,0.0434,Upregulated
38,MMP9,18.68,LUAD,12,Oncogene,2.47,0.0051,0.0007,Upregulated
43,CD274,23.19,LUAD,17,Tumor Suppressor,0.01,0.0160,0.0496,Upregulated
45,LAG3,18.25,LUAD,20,Tumor Suppressor,1.20,0.0013,0.0277,Upregulated
50,SOX2,24.39,LUAD,17,Oncogene,-1.00,0.0315,0.0228,Downregulated
51,NANOG,20.50,LUAD,5,Oncogene,-3.25,0.0439,0.0314,Downregulated
52,POU5F1,23.79,LUAD,17,Oncogene,0.63,0.0368,0.0293,Upregulated
53,VIM,22.90,LUAD,17,Tumor Suppressor,-3.71,0.0402,0.0451,Downregulated
55,SNAI1,23.44,LUAD,2,Tumor Suppressor,0.34,0.0090,0.0141,Upregulated
62,FN1,21.57,LUAD,2,Oncogene,-2.98,0.0171,0.0232,Downregulated
67,MKI67,21.04,LUAD,11,Tumor Suppressor,-3.32,0.0378,0.0493,Downregulated
69,TOP2A,24.74,LUAD,6,Tumor Suppressor,0.25,0.0451,0.0269,Upregulated
70,GATA3,20.44,LUAD,5,Tumor Suppressor,0.33,0.0253,0.0155,Upregulated
73,AR,21.31,LUAD,6,Tumor Suppressor,3.81,0.0448,0.0082,Upregulated
74,RUNX1,19.14,LUAD,22,Oncogene,0.13,0.0195,0.0456,Upregulated
75,IDH1,19.58,LUAD,11,Oncogene,-1.42,0.0006,0.0411,Downregulated
76,IDH2,20.43,LUAD,16,Oncogene,2.36,0.0453,0.0475,Upregulated
80,RET,22.26,LUAD,6,Tumor Suppressor,-3.80,0.0475,0.0466,Downregulated
86,KEAP1,19.59,LUAD,3,Tumor Suppressor,-2.75,0.0337,0.0494,Downregulated
88,NF1,22.74,LUAD,20,Tumor Suppressor,0.39,0.0396,0.0297,Upregulated
91,PALB2,19.26,LUAD,9,Oncogene,-1.76,0.0248,0.0421,Downregulated
92,RAD51,20.22,LUAD,1,Tumor Suppressor,3.64,0.0030,0.0419,Upregulated
94,MSH2,20.42,LUAD,7,Oncogene,0.43,0.0221,0.0208,Upregulated

# **Biological Interpretation**

Candidate biomarkers satisfy two important criteria:

* High expression

* Statistical significance

These genes deserve further investigation because they may:

- distinguish cancer from normal tissue

- predict prognosis

- guide targeted therapies

- serve as diagnostic biomarkers

In [ ]:
#Candidate Oncogenes
candidate_oncogenes = df[
    (df["Gene_Type"]=="Oncogene") &
    (df["Expression"]>18)
]

candidate_oncogenes

,Gene,Expression,Cancer_Type,Chromosome,Gene_Type,Log2FC,P_Value,Adjusted_P_Value,Status
1,BRCA1,24.01,LUAD,17,Oncogene,-0.06,0.0059,0.0051,Downregulated
25,NFKB1,20.70,LUAD,1,Oncogene,1.57,0.0293,0.0235,Upregulated
35,BAX,21.17,LUAD,1,Oncogene,1.62,0.0453,0.0434,Upregulated
38,MMP9,18.68,LUAD,12,Oncogene,2.47,0.0051,0.0007,Upregulated
50,SOX2,24.39,LUAD,17,Oncogene,-1.00,0.0315,0.0228,Downregulated
51,NANOG,20.50,LUAD,5,Oncogene,-3.25,0.0439,0.0314,Downregulated
52,POU5F1,23.79,LUAD,17,Oncogene,0.63,0.0368,0.0293,Upregulated
62,FN1,21.57,LUAD,2,Oncogene,-2.98,0.0171,0.0232,Downregulated
74,RUNX1,19.14,LUAD,22,Oncogene,0.13,0.0195,0.0456,Upregulated
75,IDH1,19.58,LUAD,11,Oncogene,-1.42,0.0006,0.0411,Downregulated
76,IDH2,20.43,LUAD,16,Oncogene,2.36,0.0453,0.0475,Upregulated
91,PALB2,19.26,LUAD,9,Oncogene,-1.76,0.0248,0.0421,Downregulated
94,MSH2,20.42,LUAD,7,Oncogene,0.43,0.0221,0.0208,Upregulated

# **Research Interpretation**

Highly expressed oncogenes often represent molecular drivers of tumor progression.

Many targeted cancer therapies have been developed against activated oncogenes such as:

- EGFR

- ALK

- BRAF

- ROS1

These genes are routinely evaluated in precision oncology.

# **Mini Research Project**

Assume you are a computational biologist studying Lung Adenocarcinoma.

Your objectives are:

1. Load the LUAD dataset.

2. Identify highly expressed genes.

3. Count upregulated genes.

4. Count tumor suppressor genes.

5. Identify statistically significant genes.

6. Find candidate biomarkers.

7. Write a biological interpretation summarizing your findings.

In [ ]:
print("Dataset Shape:")
print(df.shape)

print("\nAverage Expression:")
print(df["Expression"].mean())

print("\nHighly Expressed Genes:")
print(df[df["Expression"]>18])

print("\nGene Type Count:")
print(df["Gene_Type"].value_counts())

print("\nSignificant Genes:")
print(df[df["Adjusted_P_Value"]<0.05])

print("\nCandidate Biomarkers:")
print(
    df[
        (df["Expression"]>18) &
        (df["Adjusted_P_Value"]<0.05)
    ]
)

Dataset Shape:
(100, 9)

Average Expression:
14.466666666666667

Highly Expressed Genes:
      Gene  Expression Cancer_Type  Chromosome         Gene_Type  Log2FC  \
1    BRCA1       24.01        LUAD          17          Oncogene   -0.06
2     EGFR       19.64        LUAD          20  Tumor Suppressor   -2.44
7   PIK3CA       22.32        LUAD          15  Tumor Suppressor   -2.58
9     PTEN       19.16        LUAD           4  Tumor Suppressor    3.63
11   CCND1       24.40        LUAD           7  Tumor Suppressor   -1.04
12   ERBB2       21.65        LUAD          19  Tumor Suppressor   -3.88
25   NFKB1       20.70        LUAD           1          Oncogene    1.57
33   CHEK2       23.98        LUAD           9  Tumor Suppressor    1.93
34    BCL2       24.31        LUAD           5  Tumor Suppressor    1.58
35     BAX       21.17        LUAD           1          Oncogene    1.62
38    MMP9       18.68        LUAD          12          Oncogene    2.47
43   CD274       23.19        LUAD          17  Tumor Suppressor    0.01
45    LAG3       18.25        LUAD          20  Tumor Suppressor    1.20
50    SOX2       24.39        LUAD          17          Oncogene   -1.00
51   NANOG       20.50        LUAD           5          Oncogene   -3.25
52  POU5F1       23.79        LUAD          17          Oncogene    0.63
53     VIM       22.90        LUAD          17  Tumor Suppressor   -3.71
55   SNAI1       23.44        LUAD           2  Tumor Suppressor    0.34
62     FN1       21.57        LUAD           2          Oncogene   -2.98
67   MKI67       21.04        LUAD          11  Tumor Suppressor   -3.32
69   TOP2A       24.74        LUAD           6  Tumor Suppressor    0.25
70   GATA3       20.44        LUAD           5  Tumor Suppressor    0.33
73      AR       21.31        LUAD           6  Tumor Suppressor    3.81
74   RUNX1       19.14        LUAD          22          Oncogene    0.13
75    IDH1       19.58        LUAD          11          Oncogene   -1.42
76    IDH2       20.43        LUAD          16          Oncogene    2.36
80     RET       22.26        LUAD           6  Tumor Suppressor   -3.80
86   KEAP1       19.59        LUAD           3  Tumor Suppressor   -2.75
88     NF1       22.74        LUAD          20  Tumor Suppressor    0.39
91   PALB2       19.26        LUAD           9          Oncogene   -1.76
92   RAD51       20.22        LUAD           1  Tumor Suppressor    3.64
94    MSH2       20.42        LUAD           7          Oncogene    0.43

    P_Value  Adjusted_P_Value         Status
1    0.0059            0.0051  Downregulated
2    0.0024            0.0043  Downregulated
7    0.0050            0.0042  Downregulated
9    0.0237            0.0493    Upregulated
11   0.0217            0.0186  Downregulated
12   0.0200            0.0407  Downregulated
25   0.0293            0.0235    Upregulated
33   0.0194            0.0188    Upregulated
34   0.0481            0.0144    Upregulated
35   0.0453            0.0434    Upregulated
38   0.0051            0.0007    Upregulated
43   0.0160            0.0496    Upregulated
45   0.0013            0.0277    Upregulated
50   0.0315            0.0228  Downregulated
51   0.0439            0.0314  Downregulated
52   0.0368            0.0293    Upregulated
53   0.0402            0.0451  Downregulated
55   0.0090            0.0141    Upregulated
62   0.0171            0.0232  Downregulated
67   0.0378            0.0493  Downregulated
69   0.0451            0.0269    Upregulated
70   0.0253            0.0155    Upregulated
73   0.0448            0.0082    Upregulated
74   0.0195            0.0456    Upregulated
75   0.0006            0.0411  Downregulated
76   0.0453            0.0475    Upregulated
80   0.0475            0.0466  Downregulated
86   0.0337            0.0494  Downregulated
88   0.0396            0.0297    Upregulated
91   0.0248            0.0421  Downregulated
92   0.0030            0.0419    Upregulated
94   0.0221            0.0208    Upregulated

Gene Type Count:
Gene_Type
Tumor Suppressor    57
Oncogene            43
Name: count, dtype: int64

Significant Genes:
     Gene  Expression Cancer_Type  Chromosome         Gene_Type  Log2FC  \
0    TP53       12.49        LUAD           7          Oncogene    0.62
1   BRCA1       24.01        LUAD          17          Oncogene   -0.06
2    EGFR       19.64        LUAD          20  Tumor Suppressor   -2.44
3    KRAS       16.97        LUAD           4  Tumor Suppressor    1.78
4     MYC        8.12        LUAD           5          Oncogene   -1.75
..    ...         ...         ...         ...               ...     ...
94   MSH2       20.42        LUAD           7          Oncogene    0.43
95   MSH6       14.88        LUAD          18          Oncogene    0.89
96   MLH1       15.45        LUAD           8  Tumor Suppressor   -0.64
97   PMS2       13.55        LUAD           1          Oncogene   -2.02
98   POLE        5.51        LUAD          11  Tumor Suppressor   -1.15

    P_Value  Adjusted_P_Value         Status
0    0.0008            0.0309    Upregulated
1    0.0059            0.0051  Downregulated
2    0.0024            0.0043  Downregulated
3    0.0021            0.0351    Upregulated
4    0.0428            0.0037  Downregulated
..      ...               ...            ...
94   0.0221            0.0208    Upregulated
95   0.0444            0.0137    Upregulated
96   0.0176            0.0029  Downregulated
97   0.0059            0.0432  Downregulated
98   0.0072            0.0407  Downregulated

[98 rows x 9 columns]

Candidate Biomarkers:
      Gene  Expression Cancer_Type  Chromosome         Gene_Type  Log2FC  \
1    BRCA1       24.01        LUAD          17          Oncogene   -0.06
2     EGFR       19.64        LUAD          20  Tumor Suppressor   -2.44
7   PIK3CA       22.32        LUAD          15  Tumor Suppressor   -2.58
9     PTEN       19.16        LUAD           4  Tumor Suppressor    3.63
11   CCND1       24.40        LUAD           7  Tumor Suppressor   -1.04
12   ERBB2       21.65        LUAD          19  Tumor Suppressor   -3.88
25   NFKB1       20.70        LUAD           1          Oncogene    1.57
33   CHEK2       23.98        LUAD           9  Tumor Suppressor    1.93
34    BCL2       24.31        LUAD           5  Tumor Suppressor    1.58
35     BAX       21.17        LUAD           1          Oncogene    1.62
38    MMP9       18.68        LUAD          12          Oncogene    2.47
43   CD274       23.19        LUAD          17  Tumor Suppressor    0.01
45    LAG3       18.25        LUAD          20  Tumor Suppressor    1.20
50    SOX2       24.39        LUAD          17          Oncogene   -1.00
51   NANOG       20.50        LUAD           5          Oncogene   -3.25
52  POU5F1       23.79        LUAD          17          Oncogene    0.63
53     VIM       22.90        LUAD          17  Tumor Suppressor   -3.71
55   SNAI1       23.44        LUAD           2  Tumor Suppressor    0.34
62     FN1       21.57        LUAD           2          Oncogene   -2.98
67   MKI67       21.04        LUAD          11  Tumor Suppressor   -3.32
69   TOP2A       24.74        LUAD           6  Tumor Suppressor    0.25
70   GATA3       20.44        LUAD           5  Tumor Suppressor    0.33
73      AR       21.31        LUAD           6  Tumor Suppressor    3.81
74   RUNX1       19.14        LUAD          22          Oncogene    0.13
75    IDH1       19.58        LUAD          11          Oncogene   -1.42
76    IDH2       20.43        LUAD          16          Oncogene    2.36
80     RET       22.26        LUAD           6  Tumor Suppressor   -3.80
86   KEAP1       19.59        LUAD           3  Tumor Suppressor   -2.75
88     NF1       22.74        LUAD          20  Tumor Suppressor    0.39
91   PALB2       19.26        LUAD           9          Oncogene   -1.76
92   RAD51       20.22        LUAD           1  Tumor Suppressor    3.64
94    MSH2       20.42        LUAD           7          Oncogene    0.43

    P_Value  Adjusted_P_Value         Status
1    0.0059            0.0051  Downregulated
2    0.0024            0.0043  Downregulated
7    0.0050            0.0042  Downregulated
9    0.0237            0.0493    Upregulated
11   0.0217            0.0186  Downregulated
12   0.0200            0.0407  Downregulated
25   0.0293            0.0235    Upregulated
33   0.0194            0.0188    Upregulated
34   0.0481            0.0144    Upregulated
35   0.0453            0.0434    Upregulated
38   0.0051            0.0007    Upregulated
43   0.0160            0.0496    Upregulated
45   0.0013            0.0277    Upregulated
50   0.0315            0.0228  Downregulated
51   0.0439            0.0314  Downregulated
52   0.0368            0.0293    Upregulated
53   0.0402            0.0451  Downregulated
55   0.0090            0.0141    Upregulated
62   0.0171            0.0232  Downregulated
67   0.0378            0.0493  Downregulated
69   0.0451            0.0269    Upregulated
70   0.0253            0.0155    Upregulated
73   0.0448            0.0082    Upregulated
74   0.0195            0.0456    Upregulated
75   0.0006            0.0411  Downregulated
76   0.0453            0.0475    Upregulated
80   0.0475            0.0466  Downregulated
86   0.0337            0.0494  Downregulated
88   0.0396            0.0297    Upregulated
91   0.0248            0.0421  Downregulated
92   0.0030            0.0419    Upregulated
94   0.0221            0.0208    Upregulated

# **Research Reflection**

This exploratory analysis closely resembles the initial stages of transcriptomic studies performed on RNA-Seq datasets. By integrating data loading, filtering, statistical evaluation, and biological interpretation, I gained practical experience in analyzing gene expression data using Pandas. These computational skills complement my undergraduate research on transcriptome-based analysis of competing endogenous RNA (ceRNA) networks in lung adenocarcinoma and strengthen my ability to independently investigate large-scale biomedical datasets.

# **Career Connection**

The analytical workflow developed in this notebook reflects common tasks performed by:

- Computational Biologists
- Bioinformaticians
- Cancer Genomics Researchers
- Precision Medicine Scientists
- Biomedical Data Scientists

Mastering these exploratory data analysis techniques provides an essential foundation for advanced analyses such as differential gene expression, pathway enrichment, machine learning, and biomarker discovery.

## **Part 10-F Summary**

In this section, I performed a complete exploratory analysis of a simulated Lung Adenocarcinoma (LUAD) RNA-Seq dataset. By combining data exploration, filtering, statistical evaluation, and biological interpretation, I developed a research-oriented workflow similar to those used in computational biology laboratories. This analysis demonstrated how Pandas can be applied to identify biologically meaningful genes and prepare transcriptomic datasets for visualization and more advanced downstream analyses.

## **Key Takeaways**

- Combined multiple Pandas techniques into a complete exploratory analysis.
- Identified highly expressed genes and candidate biomarkers.
- Evaluated gene regulation status.
- Interpreted statistically significant genes.
- Connected computational analyses to real-world cancer genomics research.
- Prepared the LUAD dataset for visualization and downstream bioinformatics analyses.

# **Part 10G - Research Reflection, Best Practices & Career Connection**
Computational biology is more than writing Python code.

Successful researchers must also understand:

- Why an analysis is performed.
- How to interpret biological results.
- How to maintain data quality.
- How to create reproducible workflows.
- How computational analyses support experimental biology.

In this section, we reflect on the computational workflow completed in this notebook and discuss how these skills translate into real-world biomedical research.

Research Notes

Exploratory Data Analysis (EDA) is one of the first stages of every computational biology project.

Before researchers perform:

- Differential Gene Expression Analysis
- Gene Ontology (GO) Enrichment
- KEGG Pathway Analysis
- Protein–Protein Interaction Networks
- Machine Learning
- Survival Analysis

they first ensure that the dataset is:

* Correctly imported

* Properly structured

* Free from major quality issues

* Statistically summarized

* Biologically interpretable

Skipping these quality-control steps can lead to misleading biological conclusions.

# **Best Practices for Biomedical Data Analysis**

Professional computational biologists generally follow these best practices:

**Always inspect the dataset before analysis.**

Use:

- head()
- tail()
- shape
- info()

to understand the dataset.



**Never ignore missing values.**

Investigate why data are missing before deciding whether to remove or replace observations.



**Use meaningful variable names.**

Avoid generic names such as:

data1

table

Instead use names such as:

gene_expression

clinical_data

candidate_biomarkers



**Keep raw data unchanged.**

Always create cleaned copies rather than modifying the original dataset directly.



**Save intermediate results.**

Export filtered datasets as CSV files to improve reproducibility.



**Document every analysis.**

Explain what each code cell accomplishes and why it is biologically meaningful.

Common Mistakes Made by Beginners

When starting computational biology with Pandas, students often make mistakes such as:

* Ignoring missing values.

* Using incorrect column names.

* Forgetting to verify data types.

* Filtering genes without considering statistical significance.

* Modifying the original dataset instead of creating a cleaned copy.

* Performing analyses without documenting biological interpretations.

Avoiding these mistakes improves both computational accuracy and scientific reproducibility.

# **Connecting This Notebook to My Undergraduate Research**

During my undergraduate dissertation titled:

**"Competing Endogenous RNA (ceRNA) Network Predicts Prognosis of Lung Adenocarcinoma"**

I analyzed transcriptomic data using publicly available bioinformatics resources.

The analyses focused on:

- Differential gene expression
- ceRNA network construction
- Prognostic biomarkers
- Functional interpretation

Through this notebook, I learned how similar transcriptomic datasets can be explored programmatically using Pandas.

Instead of relying solely on web-based platforms, I can now import, inspect, clean, filter, and summarize gene expression datasets using Python.

These computational skills strengthen my ability to perform independent and reproducible bioinformatics analyses.

# **Career Connection**

The computational techniques introduced in this notebook are directly applicable to research and industry positions in:

- Computational Biology
- Bioinformatics
- Cancer Genomics
- Biomedical Data Science
- Precision Medicine
- Drug Discovery
- Clinical Genomics
- AI-driven Healthcare
- Systems Biology

Researchers working at institutions such as:

- IISc
- IITs
- AIIMS
- IGIB
- THSTI
- NCBS
- CCMB
- NII

regularly use Python and Pandas to analyze transcriptomic, genomic, proteomic, and clinical datasets.

Developing these computational skills provides a strong foundation for future research internships, graduate studies, and doctoral research.

# **Future Extensions of This Project**

The LUAD dataset analyzed in this notebook will continue to be used throughout the remainder of this repository.

Future notebooks will build upon today's analysis.

**Day 11**

 Visualize gene expression patterns.

**↓**

**Day 12**

 Analyze DNA sequences associated with selected genes.

**↓**

**Day 13**

 Process FASTA sequence files.

**↓**

**Day 14**

 Perform comprehensive gene expression analysis.

**↓**

**Day 15**

 Integrate all analyses into a complete mini bioinformatics project.

This progressive workflow reflects how computational biology projects evolve from raw datasets into biologically meaningful conclusions.

# **Personal Reflection**

Before learning Python, I primarily explored transcriptomic datasets using online bioinformatics platforms.

Developing programming skills has enabled me to better understand how biological data are imported, processed, analyzed, and interpreted computationally.

This notebook represents an important step toward integrating molecular biology with computational approaches and strengthens my preparation for research in bioinformatics, cancer genomics, and biomedical data science.

Rather than simply applying existing software tools, I am gradually developing the ability to perform reproducible computational analyses independently using Python.

# **Recommended Resources for Further Learning**

To continue developing computational biology skills, the following resources are recommended:

**Python & Data Analysis**

- Pandas Documentation
- NumPy Documentation
- Matplotlib Documentation
- Biopython Documentation

**Biological Databases**

- The Cancer Genome Atlas (TCGA)
- Gene Expression Omnibus (GEO)
- Ensembl
- NCBI Gene
- UniProt

**Bioinformatics Learning**

- Rosalind Bioinformatics Problems
- EMBL-EBI Training
- Galaxy Training Network

Exploring these resources will strengthen both programming proficiency and biological interpretation skills.

# **Part 10G Summary**

In this section, I reflected on the broader role of exploratory data analysis in computational biology and connected the skills developed throughout this notebook to real-world transcriptomic research. I reviewed best practices for handling biomedical datasets, identified common pitfalls encountered during data analysis, and considered how programming complements experimental biology. This reflection highlights the importance of reproducible computational workflows and demonstrates how Python can be integrated into modern bioinformatics and cancer genomics research.

# **Key Takeaways**

* Exploratory data analysis is a critical step before advanced bioinformatics analyses.

* High-quality computational research depends on clean, well-documented datasets.

* Reproducibility and careful documentation are essential in biomedical research.

* Programming enables independent analysis of transcriptomic datasets.

* Computational biology combines biological knowledge with statistics, programming, and data science.

* The skills developed in this notebook provide a strong foundation for future research in genomics, bioinformatics, and biomedical data science.

# **Day 10 Learning Journey**

Throughout this notebook, we completed the following workflow:

**Part 10-A**
* Introduction to Pandas

* Understanding biomedical datasets

* Creating a realistic LUAD RNA-Seq dataset

* Saving datasets as CSV files



**Part 10-B**

* Loading datasets

* Exploring data structure

* Understanding DataFrames

* Dataset quality assessment



**Part 10-C**

* Descriptive statistics

* Mean

* Median

* Standard deviation

* Quartiles

* Biological interpretation



**Part 10-D**

* Filtering biologically relevant genes

* Sorting genes

* Ranking candidate biomarkers

* Selecting oncogenes

* Selecting tumor suppressor genes



**Part 10-E**

* Detecting missing values

* Cleaning biological datasets

* Replacing missing observations

* Preparing high-quality datasets



**Part 10-F**

* Mini RNA-Seq exploratory analysis

* Identifying candidate biomarkers

* Biological interpretation



**Part 10-G**

* Research reflection

* Best practices

* Career connection

* Future applications

Together, these sections represent a complete exploratory transcriptomic analysis workflow.

## ** Complete LUAD Computational Biology Workflow**

```text
                    LUAD RNA-Seq Dataset
                             │
                             ▼
                  Import CSV using Pandas
                             │
                             ▼
                 Explore Dataset Structure
                             │
                             ▼
              Descriptive Statistical Analysis
                             │
                             ▼
              Data Cleaning & Missing Values
                             │
                             ▼
              Filter Biologically Relevant Genes
                             │
                             ▼
                Rank Candidate Biomarkers
                             │
                             ▼
                Biological Interpretation
                             │
                             ▼
                  Export Cleaned Gene Lists
                             │
                             ▼
            Ready for Data Visualization (Day 11)
```

# **What I Learned**

By completing this notebook, I learned how to:

* Import biological datasets using Pandas

* Explore dataset structure

* Understand DataFrames

* Calculate descriptive statistics

* Interpret transcriptomic data

* Detect missing values

* Clean biological datasets

* Filter genes based on biological criteria

* Identify candidate biomarkers

* Export processed datasets

* Connect computational analyses with biological interpretation

These skills form an essential foundation for computational biology and bioinformatics research.

# **Biological Significance**

Although this notebook used a simulated Lung Adenocarcinoma (LUAD) dataset, the computational workflow closely resembles analyses performed on real transcriptomic datasets obtained from repositories such as:

- The Cancer Genome Atlas (TCGA)

- Gene Expression Omnibus (GEO)

- ArrayExpress

- cBioPortal

The techniques learned throughout this notebook are directly applicable to real-world RNA-Seq studies involving cancer genomics, biomarker discovery, and precision medicine.

# **Skills Acquired**

After completing Day 10, I am now able to:

• Import CSV datasets

• Work with Pandas DataFrames

• Explore transcriptomic datasets

• Calculate descriptive statistics

• Detect and handle missing values

• Filter biologically meaningful genes

• Rank candidate biomarkers

• Export cleaned datasets

• Interpret biological findings

• Build reproducible computational workflows

# **Research and Career Applications**

The computational techniques learned in this notebook are fundamental to research in:

* Computational Biology

* Bioinformatics

* Cancer Genomics

* Biomedical Data Science

* Precision Medicine

* Drug Discovery

* Clinical Genomics

* AI-assisted Healthcare

These skills are widely used in universities, research institutes, hospitals, biotechnology companies, and pharmaceutical industries.

# **Repository Roadmap**

```text
Python Fundamentals
(Day 1–6)
          │
          ▼
Data Structures
(Day 7–8)
          │
          ▼
Scientific Computing
(Day 9)
          │
          ▼
Biomedical Data Analysis
(Day 10)
          │
          ▼
Genomics Visualization
(Day 11)
          │
          ▼
DNA Sequence Analysis
(Day 12)
          │
          ▼
FASTA Processing
(Day 13)
          │
          ▼
Gene Expression Analysis
(Day 14)
          │
          ▼
Mini Bioinformatics Project
(Day 15)
```

## **Final Reflection**

Completing this notebook has strengthened my understanding of how computational tools can be used to analyze biological datasets in a systematic and reproducible manner.

Through this project, I gained practical experience in importing, cleaning, exploring, filtering, and interpreting transcriptomic data using Python and Pandas. These skills complement my background in molecular biology and biotechnology and provide a strong computational foundation for future work in bioinformatics, cancer genomics, and biomedical data science.

Building this notebook has also highlighted the importance of documenting analyses clearly, connecting computational methods with biological questions, and developing reproducible research workflows. I look forward to extending these skills in the upcoming notebooks on data visualization, DNA sequence analysis, FASTA processing, and gene expression analysis.

# **Day 10 Key Takeaways**

* Learned the fundamentals of Pandas for biomedical data analysis.

* Built and explored a realistic LUAD gene expression dataset.

* Applied descriptive statistics to transcriptomic data.

* Filtered and ranked biologically relevant genes.

* Identified candidate biomarkers.

* Detected and handled missing values.

* Completed a mini RNA-Seq exploratory analysis.

* Connected computational analyses with biological interpretation.

* Developed reproducible data analysis workflows.

* Prepared the dataset for genomic visualization.

# **Recommended Reading**

To further strengthen your computational biology skills, explore the following resources:

**Python Libraries**
- Pandas Documentation
- NumPy Documentation
- Matplotlib Documentation
- Biopython Documentation

**Public Biological Databases**
- The Cancer Genome Atlas (TCGA)
- Gene Expression Omnibus (GEO)
- ArrayExpress
- Ensembl
- UniProt

**Bioinformatics Learning Platforms**
- Rosalind
- EMBL-EBI Training
- Galaxy Training Network